### ISSUE TITLE
Implement a custom pouch purge solution

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5048] opened 2018-11-28 09:52 UTC
Our users have a lot of documents on their phones. This is causing reduced with query performance, and eventually phones will run out of space altogether.

To solve this allow projects to provide configuration which defines when a document can be deleted off the phone. The document must not be deleted from the server couchdb so analytics and administrators can still access all documents. To achieve this run a service on the phone that purges a doc and modify the db-sync filter function so purged docs aren't replicated to the server.

Based on some [performance profiling](https://docs.google.com/document/d/1Y4ISvnunnYtm6Odxf2j4XloFI5vojt4hlBiB2_SHvvA/edit) we decided to implement purge using the [pouchdb remove function](https://pouchdb.com/api.html#delete_document). However it may be that removed docs no longer have enough information to be filtered out. If that's the case, implement purge by minifying the doc, eg: `{ _id: doc._id, _rev: doc._rev, _deleted: true, purged: true }`.

**Comment by SCdF** [comment] 2018-12-05 14:14
Status:
 - wrote a doc from my perspective based on my current knowledge + talking to devs + most importantly talking to tech leads: https://docs.google.com/document/d/1OqnEuSnVvxEwFx27zo6BbJQx3vQlXHpFAAowrMoediM/edit#heading=h.ktdw7luxu4ih
 - Going to work with design on answering some core questions they have to help us work toward a solution

**Comment by garethbowen** [comment] 2019-01-10 20:33
@newtewt @ngaruko I've just added this feature to 3.3.0. As it destroys data it requires significant testing to ensure it works as expected.

**Comment by SCdF** [comment] 2019-01-11 09:58
AT: here is the official documentation for the feature: https://github.com/medic/medic-docs/blob/master/configuration/purging.md

Important notes:
 - It should be impossible for it to delete data off the server (deleting out of PouchDB is the point so that's OK)
 - It should be impossible for a misconfiguration to cause the app to not start correctly

**Comment by newtewt** [comment] 2019-01-29 17:49
@SCdF  These are the steps to reproduce the update to app settings and seeing the purge has changed message. 

Log in as an offline user using chrome. Replicate and land in the app after everything has settled. 
Open the webapp in another browser(Firefox) and log in as an admin user. 
Navigate to the Admin Console.
Change the gateway number 
Save
Return to chrome as the offline user. The update dialog should be present. 
Open the browser console. 
Press Update on the dialog. 
In the console log `Purge function has changed, running purge` is displayed but hasn't been modified. Only the gateway number has been modified.

**Comment by SCdF** [comment] 2019-01-30 08:46
@newtewt this is very strange. Let me take a look

**Comment by SCdF** [comment] 2019-01-30 13:38
Found the problem, I nicked a hash function from elsewhere and didn't convert it out of being prototyped against a string correctly. This PR fixes it: https://github.com/medic/medic/pull/5317

**Comment by SCdF** [comment] 2019-01-31 11:58
I have merged this fix and backported it to 3.3.x and 3.4.x, but I haven't done any releases on these branches.

@newtewt let me know if you need me to perform any more next steps here.

**Comment by newtewt** [comment] 2019-01-31 18:51
@SCdF  may have found another issue. I am changing the date of `medic-last-purge-date` and then refreshing the app. I'm not seeing the purge rerun. The console displays ```Initiating purge
inbox.js:3 Local DB may have unreplicated records, skipping``` but my sync is up to date. Looking in local storage I don't see an entry for `medic-last-replicated-seq` and when calling `window.localStorage.getItem("medic-last-replicated-seq")` it returns `null`.

**Comment by SCdF** [comment] 2019-02-01 13:45
NB: this works in master, but is not working in 3.3.x. I'm guessing the backport is incompatible with some kind of flow here, I'm looking into it.

I'll also check the 3.4.x branch once I figure it out as well.

**Comment by SCdF** [comment] 2019-02-01 14:07
I have fixed this for 3.3.x (you need to wait for the build to complete).

The issue came about because the logic on how we replicate is different in 3.3.x compared to the version purging was originally build for and we didn't take that into account when backporting.

**Comment by SCdF** [comment] 2019-02-01 14:13
3.4.x seems to be working fine

**Comment by newtewt** [comment] 2019-02-06 18:31
Purging is working as expected. Docs are removed only from the offline user.

**Closed by newtewt** 2019-02-06 18:31 UTC
Labels: Priority: 2 - Medium, Type: Performance

**Comment by BananaAcid** [comment] 2020-05-03 18:11
So is this rolled out/documented and possible to use?

**Comment by SCdF** [comment] 2020-05-06 14:25
Answered-ish here: https://github.com/pouchdb/pouchdb/issues/802#issuecomment-624680630
