### ISSUE TITLE
Broken functionality after upgrade to 3.4 with custom locales

### ISSUE THREAD

**Issue by kitsao** [medic/medic#5617] opened 2019-04-29 14:39 UTC
_Supported languages do not show on the languages tab of languages settings, specific to webapps upgraded to 3.4.0_.

**Steps to reproduce**:
 - _Login as admin on an upgraded instance (not a fresh 3.4.0, but an upgraded webapp), e.g. `pih-malawi.dev`_
 - _Go to App Settings > Languages > Languages_

**What should happen**:
 - _Supported locales should be listed on the page, where one can set a default language among other operations. See screenshot below._
![image](https://user-images.githubusercontent.com/3928714/56903632-57ff2d80-6aa5-11e9-8a87-2ce963469417.png)

**What actually happens**:
 - _No language list is shown. See screenshot below._
![image](https://user-images.githubusercontent.com/3928714/56903688-71a07500-6aa5-11e9-84fe-b8a3700bfc83.png)

_Browser console log has the following_

```
Error loading settings TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at properties.js:81
    at createLocaleModel (translation-languages.js:25)
    at translation-languages.js:75
    at Function._.map._.collect (underscore.js:205)
    at translation-languages.js:74
    at processQueue (angular.js:17914)
    at angular.js:17962
    at Scope.$digest (angular.js:19075)
    at angular.js:19395
```

**Environment**:

- Instance: _pih-malawi.dev.medicmobile.org_
- Browser: _Chrome_
- App: _webapp_
- Version: _3.4.0_

**Other**:
_I was able to reproduce this on my local testing instance, upgraded from `3.3.0`. A fresh `3.4.0` instance works perfectly. Could be related to #5616?_

**Comment by SCdF** [comment] 2019-05-01 12:45
Looks like this has something to do with a new migration we have for translations: https://github.com/medic/medic/blob/master/api/src/migrations/convert-translation-messages.js

Either it's not firing 100% correctly or it *is* firing but then the old translation structure is being re-uploaded.

**Comment by SCdF** [comment] 2019-05-01 14:03
So I think the problem is the migration only takes into account baked in translations: not custom ones:
https://github.com/medic/medic/blob/master/api/src/migrations/convert-translation-messages.js#L24-L26

Should really be the same as:
https://github.com/medic/medic/blob/master/admin/src/js/controllers/translation-languages.js#L56-L60

**Comment by garethbowen** [comment] 2019-05-01 22:13
This has also caused a much more serious side-effect which is blocking the loading of contacts https://github.com/medic/medic-projects/issues/6237

The workaround is to update the `messages-<2-letter-code>` like so:

```json
{
  "_id": "messages-rn",
  "enabled": true,
  "values": { /* all the translations */ },
  "type": "translations",
  "code": "rn",
  "name": "Kirundi"
}
```

```json
{
  "_id": "messages-rn",
  "enabled": true,
  "generic": {},
  "custom": { /* all the translations */ },
  "type": "translations",
  "code": "rn",
  "name": "Kirundi"
}
```

**Comment by dianabarsan** [comment] 2019-06-10 10:50
For AT, the code is available on `5617-fix-translation-migration`.

The old migration has been renamed (to `convert-translation-messages-fix`) and will run again when first running 3.5 api. It will try to correct all matter of broken translation docs. 
I would suggest to test the migration when upgrading from 3.3 and 3.4, every time having at least custom locale. 
_Migrations run every time API starts. If you want to rerun the any of the migrations, edit the `migration-log` doc to remove the migration name from the list and restart API._

The PR also fixes a bug when editing a language in the admin console (the popup that edits the language name) where all properties from the `custom` list would be merged into `generic` upon saving.
When editing a translation, please make sure that all fields from `generic` and `custom` stay put! 

The PR also adds a new **authenticated** API endpoint `/api/deploy-info` which should display the same information you see at the top of the `Upgrade instance` admin page. 

Also, API should crash when any of the translation docs is malformed (f.e. have neither `generic` nor `values` properties, have either but not objects and things like that).

**Comment by ngaruko** [comment] 2019-06-12 02:20
The UI part does work -
**before** 
![image](https://user-images.githubusercontent.com/6979995/59318963-178a0500-8d1d-11e9-9405-a0dcb1be12f1.png)

**after**
![image](https://user-images.githubusercontent.com/6979995/59318978-2670b780-8d1d-11e9-84f1-31546991831b.png)

**Comment by newtewt** [comment] 2019-06-12 19:34
I've gone through migrating from 3.3 with custom local to 3.4 to the branch that fixes this a few times and seeing it work as expected. No errors in console, everything is loading, and the custom language is set. 

I also checked out the auth'd endpoint add as well to API.

Not sure if you had anything else left to check @ngaruko. Otherwise I think we can close.

**Closed** 2019-06-13 14:55 UTC
Labels: Priority: 1 - High, Type: Bug
