### ISSUE TITLE
redirect to /report/<uuid> from login page fails

### ISSUE THREAD

**Issue by mandric** [medic/medic#3234] opened 2017-03-14 15:17 UTC
On 2.10 if you send someone a link to `/reports/<uuid>` it does not get followed from the login page.

**Comment by garethbowen** [comment] 2017-03-28 09:01
@mandric This works for me locally and on a server, in firefox and chrome. If I go to the following URL I'm asked to login then taken to the reports tab with the correct report selected: https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/3EAE1203-156B-4890-BE94-F183648409B6 . Any ideas?

**Comment by mandric** [comment] 2017-03-30 15:23
Only guess is alpha.dev was not running 2.10 but I can't even load it to find out.  Just confirm you tested on 2.10 (or 2.10 branch) and we can close this.

**Comment by garethbowen** [comment] 2017-03-30 19:44
@mandric I tested on master (2.11). It's back up now if you want to try again? If it's been fixed between 2.10 and 2.11 it's probably not serious enough to backport. My main concern is it's some sort of race condition.

**Comment by garethbowen** [comment] 2017-04-04 03:56
Assigning to @mandric to reproduce.

**Comment by garethbowen** [comment] 2017-04-06 22:24
I came across this on https://clone-barefoot.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/add/issue_3281

Could be a browser specific issue or a race condition.

**Comment by SCdF** [comment] 2017-09-14 08:54
@garethbowen I get this every time on standard.app and standard.dev (running various beta of 2.13), Chrome 60, MacOS.

Here is an example of one that doesn't work: https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/800e6180f58905dafb5562238508ae17

From watching it happen:
 - The page loads (because I've already been there in the past)
 - It tries to load the reports LHS so it can then "click" the report and open it
 - This fails, and *perhaps* changes the URL to just /reports/
 - Then I get redirected to the login page, and the URL clearly doesn't contain the report UUID to redirect to

**Comment by garethbowen** [comment] 2019-09-18 20:39
Making this as a duplicate of #5955 because the new issue is more reproducible.

**Closed by garethbowen** 2019-09-18 20:39 UTC
Labels: Type: Bug
