### ISSUE TITLE
Trailing whitespace character in incoming SMS form makes sentinel throw an exception

### ISSUE THREAD

**Issue by eljhkrr** [medic/medic#4653] opened 2018-06-19 11:32 UTC
When sentinel receives an SMS report with a trailing whitespace character it throws the error below and does not process any reports coming in after the offending report

```
2018-06-19T08:52:55.125Z - error: /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/mustache/mustache.js:598
      throw new TypeError('Invalid template! Template should be a "string" ' +
      ^

TypeError: Invalid template! Template should be a "string" but "object" was given as the first argument for mustache#render(template, view, partials)
    at Object.render (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/mustache/mustache.js:598:13)
    at Object.exports.render (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/lib/template.js:41:19)
    at addMessage (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/lib/messages.js:65:27)
    at Object.addReply (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/lib/messages.js:208:9)
    at addErrorsToDoc (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/transitions/accept_patient_reports.js:123:18)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/transitions/accept_patient_reports.js:200:17
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/lib/validation.js:259:13
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/async/dist/async.js:421:16
    at iterateeCallback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/async/dist/async.js:924:17)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/async/dist/async.js:906:16
```
Removing the whitespace character unjams sentinel and it continues processing reports normally.

Discussion in https://github.com/medic/medic-projects/issues/4114

- Instance: https://amref-ethiopia.app.medicmobile.org
- Version: 2.14.0

**Comment by garethbowen** [comment] 2018-06-20 04:28
Thanks for the report!

I'm having trouble reproducing the error - @eljhkrr @billwambua do you know the uuid of the report that originally caused the error? Do you have a test environment I can test on?

**Comment by billwambua** [comment] 2018-06-20 07:40
@garethbowen I believe the uuid was `a33446174d79529d6e7c3c5294dbb9d8`. It was edited and a fake Patient ID and a male gender code added both of which were missing.

**Comment by eljhkrr** [comment] 2018-06-20 08:32
I didn't note the form uuid for the latest occurrence but the scenario I encountered was exactly the same as noted in this comment https://github.com/medic/medic-projects/issues/4114#issuecomment-391724058 and the fix mentioned worked. We don't have test environment for this instance.

**Comment by derickl** [comment] 2019-04-26 08:28
@eljhkrr @billwambua I've been unable to reproduce this with the latest master. Could you both try reproduce this on your end and share the exact set of circumstances/inputs that lead to this error?

**Comment by kennsippell** [comment] 2019-08-09 01:26
@eljhkrr @billwambua @derickl Any word on a repro of this? Also just tried to set this up and can't reproduce. I believe we should close this unless we can confirm this is still impactful?

**Comment by kennsippell** [comment] 2019-08-13 05:57
Discussed this with @eljhkrr, and this has no been reproduced for some time.

**Closed by kennsippell** 2019-08-13 05:57 UTC
Labels: Help wanted, Priority: 2 - Medium, Type: Bug
