### ISSUE TITLE
Errors on Targets page

### ISSUE THREAD

**Issue by ngaruko** [medic/medic#5438] opened 2019-02-19 23:21 UTC
**Steps to reproduce**:

* _Log on as admin_
* _Go to `/medic/_design/medic-admin/_rewrite#/targets`_
* _or click on Targets

**What should happen**:

* _The Target page should show (probably with default targets that ship with the app: speaking under correction: should we have any targets for a fresh install @abbyad ) like so: _
![image](https://user-images.githubusercontent.com/6979995/53054557-973f5a00-3509-11e9-81c8-9adda0642284.png)

**What actually happens**:
 - _Empty table (maybe expected?) with errors in console_

![image](https://user-images.githubusercontent.com/6979995/53054428-2d26b500-3509-11e9-9e80-2c198d82ba38.png)

_Even newly added target do not show on the page _

- Instance: _(gamma.dev)_
- Browser: _( Chrome)_
- Client platform: _(MacOS)_
- App: _( admin)_
- Version: _(3.3.x)_

**Comment by garethbowen** [comment] 2019-02-19 23:44
@ngaruko I could reproduce this when I created two targets with the same unique ID. I've removed a couple of duplicates from the configuration on gamma.dev which has resolved this issue, and created an issue to add validation to stop this happening again.

As this was due to misconfiguration I think this isn't a blocker for 3.3.0. What do you think?

**Comment by ngaruko** [comment] 2019-02-19 23:56
Agree with you @garethbowen . It is not a blocker for 3.3 - works well on a local environment with no duplicates.

**Comment by garethbowen** [comment] 2019-02-20 00:03
Closing - should be fixed with validation.

**Closed by garethbowen** 2019-02-20 00:03 UTC
Labels: Configuration, Priority: 1 - High, Type: Bug
