### ISSUE TITLE
Link the report to the scheduled task that caused the report to be created

### ISSUE THREAD

**Issue by SCdF** [medic/medic#4694] opened 2018-07-03 10:27 UTC
It would be immensely helpful for us to work out, when a visit comes in, the scheduled task that this visit was prompted for.

This is an important concept, because we want to be able to to show that CHWs receive our SMS and then respond to them (proving that us doing this is useful).

i.e. add a "report_uuid" property when a visit comes in that attaches to the probable sent SMS scheduled task.

It's not clear how we'd know this, but we are in a better position at runtime / sentinel time than the analytics people are in SQL land.

**Comment by garethbowen** [comment] 2018-07-03 21:20
@SCdF This looks like a duplicate of #3959 - are the more linkages that would be helpful?

**Comment by sglangevin** [comment] 2018-07-03 21:41
I think this is an improvement upon the work done in #3959. It's something I've talked with @michaelkohn before.

**Comment by wtekeu** [comment] 2018-09-25 20:01
What is the best approach to implement this?

My understanding is that when we receive the visit SMS, we have only one piece of information to play with: the patient id. So to find the report that includes the scheduled task that triggered the visit, should we just query CouchDB using the following:
`{
  "fields": {
    "patient_id": "63344"
  }
}` for a visit related to the patient with id 63344?

Is there a way to infer the report type? My guess is that if the patient has one immunization visit and a pregnancy visit pending, the above logic will fail. Plus, if this is the second pregnancy of the patient, is it enough to just pick the latest report id? Would that work for immunization and others?

**Comment by SCdF** [comment] 2018-09-26 01:29
@wtekeu I think you would want to look for "registration" forms for that patient. There is probably an existing CouchDB view for that as well. Once you've found that, take a look at some registration records to see how the schedules get written to them. Hopefully from that we could guess which registration has the valid schedule

**Comment by michaelkohn** [comment] 2018-10-08 22:11
Just moving the Slack conversation from [here](https://medic.slack.com/archives/C0813CQRX/p1538691206000100) to here.

From @wtekeu : 
> I was thinking about matching the visit with the registration via the visit incoming sms (ex: `V 43801`). It looks like the scheduled messages that you share have the incoming message in `messages[X].message` .. what do you think of such approach?

A few considerations
1. At what point is the `V` being considered as 'responding to' an outbound SMS from Medic and when is it an unsolicited Visit.  For example.... if the reminder (`scheduled_task`) from `Medic` went out on 4-October and the `V` came in on 25-October (21 days later), is this `V` really responding to that original reminder from 3 weeks ago or is this `V` really unprompted?
2. When trying to figure out which `scheduled_task` this `V` is responding to, technically we should really only consider `scheduled_tasks` whose `state` is `delivered`, though I'm not sure how reliable those `states` are so we should probably consider `sent` as well.  

I'm not sure what the magic number of days would be for # 1 (perhaps @sarahollis has an opinion), but one option would be to always associate the `V` to the most recently `sent` or `delivered` `scheduled_tasks[n]` where `scheduled_task[n+1].due` is in the future (ie the system hasn't attempted to send the next reminder yet).  If that condition cannot be met, then this `V` will not be associated to anybody.

In terms of placement of `report_uuid` I would probably recommend putting the key at the `scheduled_tasks[n]` level, so at the same level as `scheduled_tasks[n].due`.

**Comment by sarahollis** [comment] 2018-10-10 05:57
Just for some added context (responding to your initial query @michaelkohn ) we are previously been considering the V has "responding" to the task according to a 3-week buffer...meaning it counts if it's reported date was greater than the mimimum task due date (window start) and within 3 weeks of the maximum task due date (window end). 

That being said, I am not stuck to the above assumption (especially since we have not had a very reliable way of analyzing this in the past). But if we need to pick something, we can start with that.

**Comment by michaelkohn** [comment] 2018-10-10 18:29
Thanks @wtekeu ... I'm not 100% sure that my suggestion (about looking at message states/future tasks) is definitely the right thing to do, curious what others think (esp. @sarahollis as I think this request came from a convo between her and @SCdF).  Another option would be to just pick an arbitrary (well, "configurable") number of days... so an outbound reminder is considered 'responded to' if the `V` comes within 5 days (for example) of a reminder being sent.  I think this will help better understand if our reminders are actually having an influence on CHW behavior. 

One example of how my first suggestion might not be optimal.... If `scheduled_task[n+1].due` is 40 days after `scheduled_task[n]` was sent, and the `V` comes in just before `scheduled_task[n+1].due` (so 39 days after `scheduled_task[n]` was sent), to me that `V` isn't really a response to `scheduled_task[n]`, it's probably pre-empting `scheduled_task[n+1]`.

>  One last question: my understanding is that the message_uuid needs to exist in the V document but it looks like you are suggesting that a report_uuid should be at the same level as scheduled_tasks[n].due. Which one is more useful?

RE: ^^^ I may be wrong, but I don't think there is a separate `doc` (and therefore no `UUID`) for those outbound reminder messages, they just live in `scheduled_tasks` on the `P`.   And just to clarify, the `UUID` of the `P` _should_ already be on the `V` (#3959 adds a `source_id` to the `V`).

> we are previously been considering the V has "responding" to the task according to a 3-week buffer...meaning it counts if it's reported date was greater than the mimimum task due date (window start) and within 3 weeks of the maximum task due date (window end).

RE: ^^^ @sarahollis what do you mean by "it counts"?  I think you are talking about 'on time' visits, which is different than understanding if a reminder is being responded to.   Also, I'm not sure what you are using for 'window start'.  Are you talking about the `silence_for` setting (as illustrated below)? If the `V` comes a day or two before the reminder is due to be sent, it clears the entire message group and you would consider this visit to be 'on time'.  But since the reminder was never actually sent, the CHW isn't really responding to it.

![screen shot 2018-10-10 at 10 14 58 am](https://user-images.githubusercontent.com/10096985/46757484-234d9500-cc7f-11e8-95df-8e61b92995fa.png)

**Comment by michaelkohn** [comment] 2018-10-15 21:01
Thanks @sarahollis.  In the example above, there are 3 prompt messages.  Assuming that all three were sent or delivered, if the `V` comes during the blue section (so after the 3rd reminder), is your numerator 1 and denominator 3 (so 33.3% prompted were confirmed)?  Or are you looking at this at the _Group_ level (so it would be 100%)?  I assume you are doing 1 / 3 , but just want to confirm.

**Comment by sarahollis** [comment] 2018-10-16 07:17
Exactly - Group level! So 1/3.

**Comment by wtekeu** [comment] 2018-11-01 20:16
Thanks @michaelkohn for the clarification re: `report_uuid`. Do we want to consider `[scheduled_tasks[n].due, scheduled_tasks[n].due + 3 weeks]` as the "valid" window or is it fine to still consider the window `[scheduled_tasks[n].due, scheduled_task[n+1].due]`? It seems that in both cases, we are likely to make mistakes but I wonder if there is one approach which is less prone to error.

**Comment by wtekeu** [comment] 2018-11-07 18:52
@sarahollis feel free to answer if you have any insight?

**Comment by sarahollis** [comment] 2018-11-07 20:40
Hi @wtekeu if I'm understanding your question correctly, yes the numerator would be 1 and denominator 3, in that scenario you asked of earlier. Also your question on what to consider as a valid window - to me at this point it doesn't matter. We can just make am assumption and document it. Please go ahead with what you think - we did not have hard and fast definitions here at all - we were merely making some guesses. Feel free to chime in if you disagree @michaelkohn .

**Comment by ngaruko** [comment] 2019-01-17 00:18
There seems to have been a lot of discussion around this ticket. Can someone summarise how this feature is supposed to work @wtekeu @SCdF ? Or maybe a quick demo ?

**Comment by wtekeu** [comment] 2019-01-17 20:59
@ngaruko We are trying to link a report to the scheduled task that caused the report to be created. The logic that we use is to attempt to find a valid task that is either in the `deliver` or `sent` state and that is followed by a task that is still due (`due date` >  `reported date of the report`). What we then do is set the field `report_uuid ` of the valid task to the `_id` of the report doc.

So, for instance, you may register a pregnancy which will result in a number of pregnancy visit. the pregnancy registration will be stored as a doc that will include several scheduled tasks (the visits). So the goal here is that when a CHW completes the visits and submit corresponding reports, we will correctly link each visit to the appropriate scheduled tasks. The registration doc will then be updated after each visit with the corresponding report '_id`.

Let me know if you need more clarification.

**Comment by ngaruko** [comment] 2019-01-30 21:46
Thanks @wtekeu for the discussion and demo with @michaelkohn  Pushing it back to `in progress` @wtekeu ...

**Comment by garethbowen** [comment] 2019-01-30 21:59
@ngaruko Can you give some information on how this failed AT? Or was that discussed somewhere else?

**Comment by michaelkohn** [comment] 2019-01-31 18:49
@garethbowen we had a call yesterday to talk through it.  Here's what was decided.  

<img width="1348" alt="screen shot 2019-01-31 at 10 31 55 am" src="https://user-images.githubusercontent.com/10096985/52077219-51642700-2545-11e9-9867-d6ee863a27b7.png">

1. Visit does not get associated to anything since no reminder messages have been sent yet.
2. Visit does not get associated to anything since it is not responding to a reminder.  Existing functionality will set the `cleared_by` on Group 1 messages 1, 2, and 3.
3. Visit gets associated to Group 1 Message 1. Existing functionality will set the `cleared_by` on Group 1 Messages 2 and 3.
4. Visit gets associated to Group 1 Message 2. Existing functionality will set the `cleared_by` on Group 1 Message 3.
5. Visit gets associated to Group 1 Message 3.
6. Visit gets associated to Group 1 Message 3.
7. Visit gets associated to Group 1 Message 3.
8. Visit does not get associate to anything since it is within the `silence_for` range, we assume that this visit is not responding to Group 1 Message 3. Existing functionality will set the `cleared_by` on Group 2 Messages 1, 2, and 3.

For 7, ideally we wouldn't associate this visit to anything since it probably isn't responding to Group 1 Message 3, but short of hard-coding this value or adding a configuration, we don't really have a way to specify how big we want the "window" to be.

Also, visit UUIDs will be stored in an array, since there can be multiple.  We considered only keeping the first one, but decided to put it in an array instead.

@wtekeu ... also, I don't really like just calling the field `report_uuid`.  Perhaps we can call it `responded_to_by`.  I don't love that either, but it is more clear than just `report_uuid` and is more consistent with `cleared_by`.

**Comment by garethbowen** [comment] 2019-02-12 03:24
@wtekeu Is this ready for AT again? Has it been backported to 3.4.0?

**Comment by wtekeu** [comment] 2019-02-12 14:31
Yes, it is ready for AT. @SCdF did you merge it back to 3.4.0?

**Comment by SCdF** [comment] 2019-02-12 17:34
@wtekeu no I didn't. Unless something else is specified, reviewers will usually just merge to master, and you can use that as carte-blanch to cherry pick those commits into wherever they are supposed to go.

Feel free to drop me a line on slack if the back-porting / forward-porting process is unclear :-)

**Comment by wtekeu** [comment] 2019-02-12 17:51
@garethbowen backport to 3.4.0 done. Ready for AT.

**Comment by dianabarsan** [comment] 2019-02-14 07:34
I found an issue related to this while writing up Sentinel E2E tests.

Currently, there are 2 mechanisms that update registrations as part of `accept_patient_reports`:
1. the old SilenceReminders mechanism
2. the new addReportUUIDToRegistration mechanism

The `addReportUUIDToRegistration` runs first and updates the registration. If `SilenceReminders` wants to silence a task from same registration, the second save results in a conflict, thus not silencing the required tasks. 

@wtekeu @garethbowen do you think I should open a new issue or we can fix this as part of this? 

I'm also noticing that, if there are multiple registrations that have tasks that should be `responded_by` the visit, only one of them will get the marked task. I'm not sure if this is desired behavior or not.  

I'm pretty sure my configuration is dodgy and likely not something that will be exactly replicated in actual configs, but I'm adding it for reference:

```
{
  transitions: { accept_patient_reports: true },
  patient_reports: [{
    form: 'SILENCE1',
    messages: [],
    silence_for: '1 days',
    silence_type: 'type1,type2'
  }],
  registrations: [{ form: 'form_1' }],
  forms: { form_1: { public_form: true }}
}
```

the registration (tasks have `id` fields for easy reference only), oneDay = one day in ms
```
{
  _id: uuid(),
  form: 'form_1',
  fields: { patient_id: 'patient' },
  type: 'data_record',
  reported_date: new Date().getTime(),
  scheduled_tasks: [
    { id: 1, type: 'type0', state: 'scheduled', due: new Date().getTime() + 10 * oneDay },
    { id: 2, type: 'type1', state: 'scheduled', due: new Date().getTime() - 2 * oneDay },
    { id: 3, type: 'type2', state: 'pending', due: new Date().getTime() + 3 * oneDay },
    { id: 4, type: 'type2', state: 'sent', due: new Date().getTime() - 10 * oneDay },
    { id: 5, type: 'type3', state: 'muted', due: new Date().getTime() - 10 * oneDay },
  ]
}
```

the report:
```
{
  _id: uuid(),
  type: 'data_record',
  form: 'SILENCE1',
  from: 'phone',
  fields: { patient_id: 'patient' },
  reported_date: new Date().getTime()
}
```

**Comment by garethbowen** [comment] 2019-02-14 08:35
@dianabarsan Good find. I think that should probably be fixed as part of this. Sentinel shouldn't ever conflict with itself...

**Comment by dianabarsan** [comment] 2019-02-21 11:06
I've merged this into `master`. @wtekeu , would you, please, backport it to `3.4.x`? 
There are some unit tests that need to be fixed because `3.4.x` is missing this fix: https://github.com/medic/medic/commit/d2b930ee6ab8b12f092b831c081c71f33d476773 . Thanks!

**Comment by wtekeu** [comment] 2019-02-21 15:30
@dianabarsan backport done!

**Comment by ngaruko** [comment] 2019-03-05 10:34
Hi @wtekeu Can you direct me to the documentation that was done for this? My understanding is that documentation is supposed to be done before AT.

**Comment by wtekeu** [comment] 2019-03-05 20:15
@ngaruko 

Please note that the way reminders are cleared is the following: when a report is send, we add `silence_for` to the report date to obtain an `until_date`. Then we determine all the reminders that have a due date before the `until_date`. Then we extract the unique couples `[type, group]` from these reminders then clear all the reminders with `type` and `group` matching one of these couples. Also, before clearing, we ensure that these reminders are in one of the folling states: `['pending', 'scheduled', 'muted']`.

Also note that the way we link a report to a reminder is by setting the field `responded_to_by` of the reminder to the the `_id` of the report. This field can have multiple value in case of successive linking with the array having the last `_id` of the report that was linked.

The changes that were implemented are the following:
1) if we receive a report when no reminder has been sent and `until_date` is earlier than the first reminder, we don't link.
2) if we receive a report when no reminder has been sent and `until_date` is greater than the first reminder's due date, we don't link since the report is not responding to a reminder.
3) if we receive a report with a reminder sent with a due date that is earlier that the `until_date`, we link the report to the reminder. We don't link subsequent reminders of the same group when they have a due date that is greater than `until_date` (they will be cleared).

Testing should consider each case described in this message: https://github.com/medic/medic/issues/4694#issuecomment-459460521

**Comment by ngaruko** [comment] 2019-03-12 03:20
LGTM-Thanks @wtekeu for the documentation

**Closed** 2019-03-12 08:12 UTC
Labels: Analytics, Priority: 2 - Medium, Type: Improvement
