### ISSUE TITLE
Add warning dialogue when users navigate away from a form

### ISSUE THREAD

**Issue by amandacilek** [medic/medic#4013] opened 2017-11-03 21:38 UTC
On desktop, add our warning dialogue _"This form is not finished. You will lose your data if you leave now. A form is only complete when you hit Submit. Are you sure you want to leave?"_ when users are in the middle of filling out a form on the RHS and then they click on a different item in the LHS or they click on a different page tab (basically whenever they click somewhere that would navigate away from the form).

We already show the warning dialogue when a user clicks on the form "Cancel" button (which is a very intentional "I want to close this form") so it makes sense that we add it for the above scenarios which are more ambiguous actions and not necessarily "I want to close this form".

**Comment by ngaruko** [comment] 2018-11-19 03:08
This feature seems to not work on 3.3.X. I mean, the waring prompts appears only when the user clicks the 'Cancel' button, but not on any other action that navigates away from the form (Click on LHS, change tab, browser 'back' button). Did we merge this @garethbowen @peter-ochieng ? Tested on '[gamma.dev](https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/#/messages/contact:0dbb7233-797f-48b7-9e6c-2856070dea96)` v3.3.x

**Comment by garethbowen** [comment] 2018-11-19 03:29
@ngaruko Works for me... maybe you're not modifying the form before trying to navigate away? We don't warn users that haven't changed anything because they have no work to use.

Steps I used:

1. Edit a report - I used: https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/edit/c521834d-9456-4b9c-8862-f549c395bcda
2. Change the radio selection from "yes" to "no"
3. Click on the Tasks tab

Popup:

![screenshot from 2018-11-19 16-29-10](https://user-images.githubusercontent.com/2064938/48684797-4b35fe00-ec18-11e8-9f37-624db195a454.png)

**Comment by ngaruko** [comment] 2018-11-19 03:45
Thanks @garethbowen. So, this only applies for existing forms that are being modified/edited? and not on new forms. I would think that this applies also to new forms/reports when the user has completed a few fields on the form and tries to navigate away, aye @amandacilek ?. At least the 'Cancel' button works that way...

**Comment by garethbowen** [comment] 2018-11-19 03:47
@ngaruko Yes it is supposed to work with new forms too. I've just tested and it doesn't work for me either.

@peter-ochieng Could you have another look at this one please?

**Comment by peter-ochieng** [comment] 2018-11-19 08:56
Sure,I'll have a look and amend the functionality to work for new forms as well.

**Comment by garethbowen** [comment] 2018-11-27 22:48
Merged and backported to `3.3.x`

**Comment by ngaruko** [comment] 2018-11-28 22:08
Thanks @peter-ochieng . Looks better at the moment. Not sure how the `exit/navigate away` logic is implemented here, but it doesn't seem to cover all possible scenarios. Eg, the following clicks navigate away from the form without issuing a warning:`Analytics` tab, Medic Mobile logo, any element in the top right menu, 'submit report' , Refresh, Home.

**Comment by garethbowen** [comment] 2018-12-20 21:44
A new patch has been merged and backported to 3.3.x

**Comment by newtewt** [comment] 2019-01-04 14:59
@peter-ochieng  I'm not seeing the warnings as described by @ngaruko  with the latest 3.3.x branch on gamma-b.

**Comment by garethbowen** [comment] 2019-01-10 00:53
Merged and backported to `3.3.x`

**Comment by newtewt** [comment] 2019-01-10 20:04
@peter-ochieng  I'm seeing the message now. However, when I open a form and then click on a tab across the top. It presents the message. Clicking no returns me to a blank page.

**Comment by garethbowen** [comment] 2019-01-25 01:53
Merged and backported to `3.3.x`

**Comment by ngaruko** [comment] 2019-01-29 04:42
Can you have a second look at this @newtewt . Seems like it still behaves as you described above on `3.3.0-beta.2`. Or was this merged later @peter-ochieng? 
[issue.mov.zip](https://github.com/medic/medic/files/2806076/issue.mov.zip)

**Comment by peter-ochieng** [comment] 2019-01-29 05:13
@ngaruko it was Merged and backported to `3.3.x` last week on Friday.

**Comment by ngaruko** [comment] 2019-01-29 17:42
Thanks @peter-ochieng .  Are browser buttons/actin meant to be covered as well? I am talking of `refresh/reload/F5` buttons, `Home` button, closing the tab altogether (not sure if this is meant to be covered by this ticket).

**Comment by peter-ochieng** [comment] 2019-01-30 06:41
@ngaruko No,I don't think browser actions were to be covered within this ticket, just the navigation actions within the app but we can still get further clarification from @garethbowen ?

**Comment by amandacilek** [comment] 2019-01-31 00:41
Hm, browser actions do seem like something we should warn about (if a desktop user tries to close a tab with a half-completed form in it, we should first present a dialogue double checking that they want to exit and lose their work).

If adding browser actions in is a bit of extra work then I am fine splitting that off and making it a separate ticket. But don't take my word for it, @garethbowen may have a reason for not warning for browser actions that I am unaware of.

**Comment by garethbowen** [comment] 2019-01-31 03:05
I think we've done enough for now - as Bede points out our user base is mostly smartphone users. Lets split the browser actions off as a separate issue, or raise one about auto saving drafts (harder but much better UX) instead or as well.

**Comment by ngaruko** [comment] 2019-01-31 22:50
Thanks @amandacilek and @garethbowen for clarifications. I have created another [issue ](https://github.com/medic/medic/issues/5325)to work on the above and assigned it to @amandacilek for further suggestions.

**Closed by ngaruko** 2019-01-31 22:50 UTC
Labels: Priority: 3 - Low, Type: Improvement

**Comment by dianabarsan** [comment] 2019-02-18 18:05
I can still see some issues regarding the implementation of this feature:

**Steps to reproduce**
- login as admin 
- go to Contacts
- open a form to add a new contact and edit something 
- open the Hamburger menu and click on About
- when the navigation warning dialog pops up, click on "Yes" (You want to navigate to the about page).

**What should happen**
- You should be redirected to the About page

**What actually happens**
- You stay in the same "Contacts" zone, but your form closes. Depending on what type of form you opened, you're either redirected to the parent contact or to no contact (if you selected to add a new district). 

Same thing happens with reports, also clicking on tabs different than current "scope" (Contacts -> click on Reports etc) yields the same result.

**Comment by garethbowen** [comment] 2019-02-18 21:45
I've raised a new issue for that bug as https://github.com/medic/medic/issues/5423
