### ISSUE TITLE
Error in creating New Area - LG Config

### ISSUE THREAD

**Issue by ngaruko** [medic/medic#5813] opened 2019-07-16 20:24 UTC
**To Reproduce**
1. Go to 'people's page'
2. Click on 'New Area'
3. `Add Family Form` 
4. Select `yes` for `Registration Check`
5. Click `Submit`
6. `Error updating ` message appears next to the Submit button ( Expected)
7. Back to `Registration Check` , select No

**Expected behavior**
The error should go away and allow the user to continue with the form

**Current behavior**

1. If the user goes back to yes, and submit, the form is submitted with an unnamed entry 
(attached screen recording) [area.mov.zip](https://github.com/medic/medic/files/3398986/area.mov.zip)
2. if the user continues (after selecting no), the error message stays until form is submitted
![image](https://user-images.githubusercontent.com/6979995/61326905-e052ca80-a86b-11e9-8a89-e8ea11bf6ff0.png)

**Environment**
- Instance: ( gamma-b.dev.medicmobile.org)
- Browser: (Firefox, Chrome, Mobile)
- Client platform: (MacOS)
- App: (webapp)
- Version: (3.6.x)

**Comment by garethbowen** [comment] 2019-07-16 21:04
@ngaruko There should be a useful error message in the console - can you please add that to this issue?

**Comment by ngaruko** [comment] 2019-07-17 02:10
Error in the console @garethbowen 
![image](https://user-images.githubusercontent.com/6979995/61341935-90d8c280-a89c-11e9-86db-636f50e59afb.png)

**Comment by derickl** [comment] 2019-07-17 12:42
Does this apply? https://medic.slack.com/archives/CBDHSGQ8L/p1563336935078000?thread_ts=1563308816.073900&cid=CBDHSGQ8L

**Comment by dianabarsan** [comment] 2019-07-17 12:43
I've replicated this in 3.3, 3.4 and 3.5 (and did not go further back). 
I'm seeing the same behavior of both submitting the form on 1st step after the 1st failure AND the "Error updating" message not being removed even after changing the value and going to the next page. 

I think part of the issue is the form itself, as much of the form sections are only relevant when `Has this Household been registered by another CHV` is `no`. 
The first time the submission fails in the example (when `Has this Household been registered by another CHV` is `yes`) is because the form is using the default `parent` field values (`"PARENT"`) and the actual failure is caused by failing to get the doc with `id === 'PARENT'`. 
If this default value is overwritten (fe by changing checkbox to `no` and then to `yes` again) there is no submission error and the doc gets created. 
_The resulting doc is an absurdity - it's a type `clinic` with fields that the form would have assigned to the secondary primary contact that would have been created alongside the clinic doc, because of how we actually select which is our primary doc in [EnketoTranslation](https://github.com/medic/medic/blob/master/webapp/src/js/services/enketo-translation.js#L355)_

We can also trigger the same behavior of submitting an absurd doc by skipping the 1st step in the video (selecting the 1st "yes") and just select "no" -> "yes" -> "submit". 

In light of this, I am not sure what to this issue is actually about? Does it just turn into resetting the submission "error" message when fields have been updated?

**Comment by dianabarsan** [comment] 2019-07-17 12:51
I just tested the same form on an LG testing instance (which runs 2.13) and can create the same empty docs by following the steps in the video.

**Comment by dianabarsan** [comment] 2019-07-17 16:57
Also, I am only seeing the errors @ngaruko is displaying in Firefox - which appears to be the same browser  from the image. No errors logged in Chrome or Chromium, so I think they are browser specific. 
All tests above were using Chrome.

**Comment by wtekeu** [comment] 2019-07-26 20:39
I was able to reproduce the error on Chrome.

doc without overriding the default `PARENT` value:
<img width="598" alt="Screen Shot 2019-07-26 at 4 33 42 PM" src="https://user-images.githubusercontent.com/1445164/61980053-85d01180-afc3-11e9-9fc1-c507db5abaa5.png">

doc after overriding the default `PARENT` value:
<img width="552" alt="Screen Shot 2019-07-26 at 4 31 40 PM" src="https://user-images.githubusercontent.com/1445164/61980065-8f597980-afc3-11e9-8c54-66df89bbc629.png">

console error:
<img width="898" alt="Screen Shot 2019-07-26 at 4 38 20 PM" src="https://user-images.githubusercontent.com/1445164/61980143-d21b5180-afc3-11e9-9e76-c28d580f7cc1.png">

Is it possible to disable the submit button when the user answers `Yes`? Again, looks like a form issue more than a code issue

**Comment by dianabarsan** [comment] 2019-07-29 12:28
@wtekeu 
This was the same conclusion I've drawn (that the form is clearly flawed), however there also is a webapp bug here, where the "Error submitting form" message doesn't disappear when fields are edited, or even when switching form pages. 
Please see discussion here: https://medic.slack.com/archives/C024KTGRW/p1563394014171700

**Comment by dianabarsan** [comment] 2019-09-10 13:36
Ready for AT on `5813-bug-with-area-creation` . This branch fixes the sticky error message.

**Comment by ngaruko** [comment] 2019-09-11 07:13
LGTM

**Closed** 2019-09-11 09:22 UTC
Labels: Priority: 2 - Medium, Type: Bug
