### ISSUE TITLE
Loading the Contact list is slower in 3.5.0

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5755] opened 2019-06-26 20:21 UTC
**Describe the bug**
Performance timings (stopwatch) are slower now when loading the contacts tab on all devices (chrome desktop, tecno wx3, and J5 in the mobile app)

**To Reproduce**
1. Install 3.5.0.beta.2 
2. Seed with data
3. Log in as restricted user from seed data
4. Click on contacts tab. Start Timer here.

**Expected behavior**
When the loading finishes on RHS of desktop this is the end. While on mobile app the contact list displays. 
Time has increased ~5-6 seconds up from ~1-2 seconds

**Environment**
- Instance: gamma.dev.medicmobile.org
- Browser: Chrome, Mobile App
- Client platform: Linux, Android
- App: webapp
- Version: 3.5.0.beta.2

Details on times here. 
https://docs.google.com/spreadsheets/d/13GW_gpZElcmW9AOs5r1EXwKligCDECdHVP_3aNcwqhw/edit#gid=0

**Comment by garethbowen** [comment] 2019-06-26 22:22
The tests are being rerun so I've blocked this awaiting confirmation of the issue.

**Comment by kennsippell** [comment] 2019-06-26 23:52
## Loading the List of Contacts (LHS) 

Version | 1 | 2 | 3 | 4 | 5 | Mean
-- | -- | -- | -- | -- | -- | --
3.4.x | 21.2 | 21.9 | 21.8 | 24.9 | 28.3 | 23.62
3.5.x | 26.1 | 23 | 24.7 | 26.5 | 25.6 | 25.18

Does appear slightly slower, but not a statistically significant performance difference.

## Loading a Single Contact (RHS)

This is the time from contact selection, to loading and rendering the last set of data for the selected contact (the contact summary).

On 3.4.x:

Version | Clinic_1 | Clinic_2 | Clinic_3 | Clinic_4 | Clinic_5 | Clinic_6
-- | -- | -- | -- | -- | -- | --
1 | 110 | 206 | 336 | 941 | 1854 | 2240
2 | 123 | 219 | 369 | 844 | 1767 | 2634
3 | 102 | 110 | 408 | 847 | 1852 | 2301
Mean | 111.7 | 178.3 | 371.0 | 877.3 | 1824.3 | 2391.7

On 3.5.x:

Version | Clinic_1 | Clinic_2 | Clinic_3 | Clinic_4 | Clinic_5 | Clinic_6
-- | -- | -- | -- | -- | -- | --
1 | 189 | 227 | 512 | 1102 | 2297 | 2507
2 | 208 | 259 | 461 | 996 | 2113 | 2637
3 | 205 | 251 | 515 | 989 | 2049 | 2462
Mean | 200.7 | 245.7 | 496.0 | 1029.0 | 2153.0 | 2535.3

**Comment by newtewt** [comment] 2019-06-27 00:54
@kenn Do you feel this is worth blocking 3.5.0?  It seems kinda rough to me.

**Comment by kenn** [comment] 2019-06-27 00:57
Please mention the name correctly ;)

**Comment by kennsippell** [comment] 2019-06-27 00:59
@kenn sweet name

**Comment by newtewt** [comment] 2019-06-27 00:59
Ha! Whoops sorry!

**Comment by kennsippell** [comment] 2019-06-27 04:31
This issue was largely caused [here](https://github.com/medic/medic/commit/21b3c08c10fdf8b028cabffbc2568b746d1df32a#diff-3eeb107d516b06788ab7c925732c1e65L254). I believe the fix will be to have the `content-controller` share information via `store` instead of having the `contacts` controller invoke a second call to `ContactViewModelGenerator.loadChildren`.

**Comment by kennsippell** [comment] 2019-06-28 19:11
I've been struggling a bit with establishing parity between the two builds I'm measuring. In my first round of measurement, it turns out my 3.5 build had the standard config deployed and my 3.4 build did not (user error during deployment). In my second round of measurement, it turns out the `ac1` user created by the seed-data had a properly set `contact_id` attribute in the 3.5 dataset, but did not have it set properly on the 3.4 dataset. I'm unsure if this is a user-error or tooling issue. Investigating ... These parity differences in the data resulted in some of the performance differences reported above.

Here are some updated measures for the left-side, which are the numbers reported from release testing. I see no statistically significant regression.

Desktop | 3.4 | 3.5
-- | -- | --
1 | 18 | 19
2 | 24 | 20
3 | 29 | 17
4 | 18 | 19
5 | 29 | 20
MEAN | 23.6 | 19

Techno F1 | 3.4 | 3.5
-- | -- | --
1 | 174 | 169
2 | 195 | 172
3 | 174 | 172
4 | 148 | 216
5 | 152 | 169
MEAN | 168.6 | 179.6

Most of my time continues to be focused on selecting a single contact (right-side), as I believe a regression exists there (although not as significant as reported above). I will send two pull requests for this with their own measures.

**Comment by kennsippell** [comment] 2019-07-03 07:53
The PR above is ready for AT: `5755-contacts-perf`

@newtewt I'll need your help setting up a repro of the >10 second load times reported in your excel.

**Comment by kennsippell** [comment] 2019-07-03 16:58
Went through this with @newtewt today and he helped clarify his measurement process. For each measurement, he clears the cache, resyncs data, and then measures the time-to-first-load for the tab. In contrast, I have been navigating to the tab to ensure everything is warmed and only after warming do I compare the tab's load times.

**Comment by kennsippell** [comment] 2019-07-04 07:44
So this regression is only in the "first-load time", and does not impact subsequent loads. It is caused by a need to warm the `contacts_by_type` view in 3.5, but in 3.4 this view is already warmed during bootstrap. This change is due to [this](https://github.com/medic/medic/commit/590aadedb0502ceadc76e7982b3ecdc0c4bb767a#diff-2a663112a2d4e7ebb886d473db90dd64L382) #4423 as the `PlaceHierarchy` service warmed these views indirectly via the `Contacts` service.

*Fixing This* - I'm unsure of what to actually do here, as it is unclear what view warming should happen at startup vs what view warming should happen during the user's first experience. Should we explicitly warm all views on bootstrap - we could allow the user to click a button to "use the app before it is fully optimised"? 

Alternatively, there seems to be an assumption that the `RulesEngine` service is responsible for view warming [here](https://github.com/medic/medic/blob/master/webapp/src/js/controllers/inbox.js#L203). Though that isn't at all clear from reading its code that this is part of its duties. We could continue this sort of "balancing act" by updating it to warm the `contacts_by_type` view instead of the `contacts_by_type_index_name` view.

*Quality Assurance* -- While it is not without value to measure the first-load time, I think it is more important to monitor for regressions in not-first-load times. So I recommend that we update or replace that measurement in our release testing process. @newtewt @ngaruko

**Comment by kennsippell** [comment] 2019-07-08 08:48
Ready for AT in `5755-dbwarm` and `5755-contacts-perf`

**Comment by ngaruko** [comment] 2019-07-09 04:25
@kennsippell These two branch seem slower than `master` on contact page, at least on first-load. The `not-first-load` seems a lot better but still, for the same user, it looks smoother than first-load, but not as smooth as on `master`. Tested on local. see screen recordings .
[master.mov.zip](https://github.com/medic/medic/files/3371170/master.mov.zip)
[5755-dbwarm2.mov.zip](https://github.com/medic/medic/files/3371171/5755-dbwarm2.mov.zip)

**Comment by kennsippell** [comment] 2019-07-09 05:29
Thanks for testing this @ngaruko! I think the measures are a little unclear because you loaded the reports tab before loading the contacts tab when testing `master`. This actually ends up warming up parts of the contacts tab and speeds up the tab's first-load time. 

If you try this on a mobile device, and navigate to the contacts tab as your first action for both control and experiment - I think you'll nice a huge difference. These were the times I measured:

Desktop | master | proposed
-- | -- | --
Sample 1 | 2379 | 44.3
Sample 2 | 2364 | 10.2
Sample 3 | 2278 | 37.2
MEAN | 2340 | 31

Tecno F1 | master | proposed
-- | -- | --
Sample 1 | 10576 | 350
Sample 2 | 10377 | 482
Sample 3 | 13062 | 339
MEAN | 11338 | 390

**Comment by ngaruko** [comment] 2019-07-09 10:53
Thanks @kenn for the clarification - I will close this and continue to monitor performance on large instances with feature phones! Will also pay some more attention during our release testing on a `gamma.dev`.

**Comment by ngaruko** [comment] 2019-07-09 10:55
@kenn Can you please have a look at the conflicts on the [branch](https://github.com/medic/medic/pull/5770) before we close this ?

**Comment by kenn** [comment] 2019-07-09 14:29
Please, don't mention my name. :)

**Comment by kennsippell** [comment] 2019-07-09 17:46
@ngaruko Merged conflicts on the `5755-contacts-perf` branch.

**Closed** 2019-07-10 03:57 UTC
Labels: Priority: 2 - Medium, Type: Performance
