### ISSUE TITLE
Source validation failing for Africa's Talking aggregator integration

### ISSUE THREAD

**Issue by benkags** [medic/medic#5844] opened 2019-07-28 09:24 UTC
**Describe the bug**
Requests from Africa’s talking are failing due a source validation check that ensures https & valid source IPs. Testing this further confirms it:
```
curl -X POST https://cdc-mohke-dsru.dev.medicmobile.org/api/v1/sms/africastalking/delivery-reports
https is required

curl -X POST https://cdc-mohke-dsru.dev.medicmobile.org/api/v1/sms/africastalking/incoming-messages
https is required
```
From deliberation with @garethbowen, this is likely happening because Docker infrastructure has to strip it off https when it proxies the request, a scenario likely not testing during AT due the fact that testing was done on dev environment.

**To Reproduce**
1. Have an instance running v3.6 configured for Africa's Talking integration as per the documentation [here](https://github.com/medic/medic-docs/blob/1bbe0504fc6ef084ded55a69701235e440d336ee/configuration/africas-talking.md)
2. Send message to the short code and observe server logs and you should see something similar to the logs below

**Expected behavior**
Messages should hit the instance with the correct configuration in place.

**Logs**
```
Jul 28 11:21:49 dev-test-cdc-mohke-dsru dev-test-cdc-mohke-dsru-medic-api-logs:  (dev-test-cdc-mohke-dsru-6bb57f6458-gdqrw) | [2019-07-28 08:21:49] 2019-07-28 08:21:49 WARN: Attempt to access Africa's Talking endpoint with protocol: "http", ::ffff:100.120.0.0
Jul 28 11:21:49 dev-test-cdc-mohke-dsru dev-test-cdc-mohke-dsru-medic-api-logs:  (dev-test-cdc-mohke-dsru-6bb57f6458-gdqrw) | [2019-07-28 08:21:49] RES 2e146c68-eb87-476f-b8e7-c67f56b22906 ::ffff:100.120.0.0 - POST /api/v1/sms/africastalking/incoming-messages HTTP/1.1 403 - 2.818 ms
```

```
Jul 28 11:15:22 dev-test-cdc-mohke-dsru dev-test-cdc-mohke-dsru-medic-api-logs:  (dev-test-cdc-mohke-dsru-6bb57f6458-gdqrw) | [2019-07-28 08:15:22] 2019-07-28 08:15:22 INFO: Sending 0 messages 
Jul 28 11:15:57 dev-test-cdc-mohke-dsru dev-test-cdc-mohke-dsru-haproxy:  (dev-test-cdc-mohke-dsru-6bb57f6458-gdqrw) | Jul 28 08:15:57 dev-test-cdc-mohke-dsru-6bb57f6458-gdqrw haproxy[25]: 127.0.0.1,401,GET,/_session,-,-,'-',384,0,61,'curl/7.58.0'
Jul 28 11:15:58 dev-test-cdc-mohke-dsru dev-test-cdc-mohke-dsru-medic-api-logs:  (dev-test-cdc-mohke-dsru-6bb57f6458-gdqrw) | [2019-07-28 08:15:57] 2019-07-28 08:15:57 WARN: Attempt to access Africa's Talking endpoint with protocol: "http", ::ffff:100.120.0.0 
Jul 28 11:15:58 dev-test-cdc-mohke-dsru dev-test-cdc-mohke-dsru-medic-api-logs:  (dev-test-cdc-mohke-dsru-6bb57f6458-gdqrw) | [2019-07-28 08:15:57] REQ 492b5625-c7a1-4eba-923d-10cab3cc998b ::ffff:100.120.0.0 - POST /api/v1/sms/africastalking/delivery-reports HTTP/1.1
Jul 28 11:15:58 dev-test-cdc-mohke-dsru dev-test-cdc-mohke-dsru-medic-api-logs:  (dev-test-cdc-mohke-dsru-6bb57f6458-gdqrw) | [2019-07-28 08:15:57] RES 492b5625-c7a1-4eba-923d-10cab3cc998b ::ffff:100.120.0.0 - POST /api/v1/sms/africastalking/delivery-reports HTTP/1.1 403 - 2.310 ms
```

**Environment**
- Instance: `https://cdc-mohke-dsru.dev.medicmobile.org`
- App: webapp / sms 
- Version: 3.6.0

**Comment by garethbowen** [comment] 2019-07-29 14:02
@benkags This is now ready for acceptance testing, released as `5844-fix-at-security-3.6.x`. Are you able to take some time to test this new solution before I release 3.6.1 final?

I've also updated the configuration documentation in this branch: https://github.com/medic/medic-docs/blob/0b2e78964329df555f6d5e3ad316d56a4b76cb52/configuration/africas-talking.md

**Comment by benkags** [comment] 2019-07-29 15:52
@garethbowen is there an instance where this is deployed for AT ?

**Comment by garethbowen** [comment] 2019-07-30 02:43
No, all I have is the testing release. Do you have a testing instance for this project? If not, please reach out to the site reliability team to clone your production instance so you can try this out.

**Comment by benkags** [comment] 2019-07-30 05:59
I do not have one that I can use now. The one that was at my disposal is currently set up for training.

@medic/site-reliability-engineering Kindly facilitate medic/medic-projects#6683 to enable this.

**Comment by newtewt** [comment] 2019-07-30 20:41
I have this a look on gamma.dev. I saw the issue presented in 3.6.0 then upgrade to 3.6.1 and applied to changes associated to this ticket. I'm sending and receiving messages from Africa's Talking and from the App into AT's dashboard.

I have one concern which may not be related to this.  When I go directly to messages and send a message to a valid phone number or to an existing contact it shows as sent in the webapp. Reviewing the medic-api logs I see where we are checking to send messages `[2019-07-30 20:40:22] 2019-07-30 20:40:22 INFO: Sending 0 messages ` but never one that includes that message and nothing arrives in the AT dashboard.

**Comment by newtewt** [comment] 2019-07-30 21:00
Adding some clear reproduction steps since I know we are on a larger time difference. 

Ensure AT config is enabled and working. Verified by previous messages sent. 

Navigate to the messages tab. 
Click send message
Enter a valid phone number. In this case I used my cell phone. 
Send the message.  
The message shows as sent.  No message is shown in the AT dashboard under bulk messages or the incoming tab. 
 


Navigate to the messages tab. 
Click send message
Enter a valid phone number for a contact registered in the webapp
Send the message.  
The message shows as sent.  No message is shown in the AT dashboard under bulk messages or the incoming tab.

**Comment by garethbowen** [comment] 2019-07-31 04:02
@newtewt I think what's happening is the message is being sent immediately - it never goes into the backlog so that backlog checker isn't finding it and the count is always 0. The backlog processor is used for checking for scheduled messages that are now pending, or messages that failed to send but should be retried later.

That doesn't explain why it's not showing up in AT. I don't have access to gamma.dev on this machine yet, nor do I have your AT login, so it's hard to work out what's going on. Ping me when you come online in the morning and maybe we can work together to debug it?

**Comment by newtewt** [comment] 2019-07-31 15:09
I'm sending and receiving messages from gamma.dev. Getting scheduled messages sent, sending straight messages from the messages tab,  and submitting SMS forms and getting auto responses. @benkags  feel free to keep this open until you get a chance to test but otherwise I think we are good.

**Comment by garethbowen** [comment] 2019-08-01 08:23
After some investigation we realised that the message was being marked as "sent" immediately due to a sentinel transition "resolve_pending" which was mistakenly enabled in the standard config as well as on gamma. Disabling this transition immediately fixed the issue. The above PR includes a change to disable the transition by default.

**Comment by garethbowen** [comment] 2019-08-02 04:15
@benkags Looks like the clone is ready to go. Let me know if you have a chance to test this and I'll get a 3.6.1 release out ASAP.

**Comment by benkags** [comment] 2019-08-05 07:30
On this today @garethbowen

**Comment by benkags** [comment] 2019-08-05 12:09
Tested the following using [cdc-mohke-dsru's config](https://github.com/medic/medic-projects/tree/b22923b11a09c33082b06e48d1aa3b9b1906cdb0/cdc-mohke-dsru)  on [cdc's clone](https://clone-cdc-mohke-dsru.dev.medicmobile.org):
- text form reports sent from a phone number registered in the system are received & captured in the instance as expected
- auto replies from these reports are appearing on AT's outbox and ultimately delivered to the recipient phone number.
- sending message back and forth using from the messages tab in the webapp has messages register in the webapp & deliveries to the recipient phone number as expected.

I think we are good to go on this one.

**Comment by benkags** [comment] 2019-08-05 12:11
The observation by @newtewt about messages not showing up on AT's dashboard may be related to an observation we observed last week where messages were dropping as per the comment [here](https://github.com/medic/medic-projects/issues/6670#issuecomment-518194066).

**Closed** 2019-08-06 22:45 UTC
Labels: Priority: 1 - High, Type: Bug
