### ISSUE TITLE
Tasks to be completed for people (family members) do not appear in a place's (household) profile

### ISSUE THREAD

**Issue by kitsao** [medic/medic#5639] opened 2019-05-03 17:16 UTC
**Describe the bug**
Tasks to be completed for a place (household) and people (family members) belonging to that place appeared in a consolidated list on the place's profile

**To Reproduce**
1. Sign in as a normal user (restricted to their place), and `user.parent.type === 'health_center'` on a v3.4.0 instance e.g. [pih-malawi.dev](pih-malawi.dev.medicmobile.org)
2. Go to a household profile with family members that have pending tasks
3. Observe the Tasks card. Notice that the family members tasks do not show on the household profile. See screenshots below: _First shows household profile (with Bird's task not showing), second shows person's profile with tasks listed_
![image](https://user-images.githubusercontent.com/3928714/57153512-2f49a180-6ddf-11e9-9792-a99f6c8154d5.png)

![image](https://user-images.githubusercontent.com/3928714/57153575-556f4180-6ddf-11e9-91e1-76a6ccf700a7.png)

**Expected behavior**
Tasks on family members should show up in Household's tasks. See below screenshot for Faith Kipong's task.
![image](https://user-images.githubusercontent.com/3928714/57153632-7b94e180-6ddf-11e9-8a90-fe18f65a5845.png)

**Logs**
None.

**Screenshots**
See above.

**Environment**
- Instance: _Any on 3.4.0, **pih-malawi.dev** is a good candidate_
- Browser: _Chrome_
- Client platform: _Linux_
- App: _webapp_
- Version: _3.4.0_

**Additional context**
Expected behavior was exhibited in prior versions (I know of 2.13 to 3.3.0). Related to #1852 and #2742

**Comment by dianabarsan** [comment] 2019-05-03 17:25
Appears to have been caused by https://github.com/medic/medic/commit/1d8ce7be236feb393d6dabdfee7de70fddd2d72b 
ContactsContent controller requires the selected contact children to be loaded before loading tasks: https://github.com/medic/medic/blob/fix-parent-tasks/webapp/src/js/controllers/contacts-content.js#L73

**Comment by dianabarsan** [comment] 2019-05-20 10:36
Ready for AT on `5639-display-children-tasks`.

**Comment by wtekeu** [comment] 2019-05-23 16:17
AT complete!

Created a task attached to a person. The task appears in the task card of the place the person belongs to (it is not the case when testing using master).
LGTM.

Merged and ready for release.

**Closed by wtekeu** 2019-05-23 16:17 UTC
Labels: Priority: 1 - High, Type: Bug
