### ISSUE TITLE
On reports tab, hide section separator lines when all of the fields from a section are hidden

### ISSUE THREAD

**Issue by amandacilek** [medic/medic#5748] opened 2019-06-24 17:53 UTC
Currently for the Muso mRDT project, we are hiding most of the fields on the Reports detail page so that supervisors can more quickly and easily find the information that they need (mainly, the Results field).

Right now, we are seeing a few extra horizontal lines which I assume are from hidden sections. When we hide a section in the report, we should also hide the separator lines from that section so that we don't end up with extra lines.

![Screen Shot 2019-06-24 at 9 10 42 AM](https://user-images.githubusercontent.com/26235957/60040537-1b4b4f00-966e-11e9-8ac9-9738d519d9d7.png)

**Comment by senseibara** [comment] 2019-06-30 19:12
@amandacilek didn't check this ticket before, but this is only happening because the labels are empty. The actual problem is,  a field without any value ( a note for example or an empty string ), will still have it's label displayed here. Putting empty labels was done on purpose as a workaround until we have this #5747 . We can rather rephrase the problem as being " Fields without any value are being displayed but there is no use to " or we can leave the possibility to hide it on purpose once #5747  is available

**Comment by maremegaye** [comment] 2019-07-24 12:12
cc @MaxDiz @Fatoufall

**Comment by MaxDiz** [comment] 2019-07-24 13:00
Hi @maremegaye this is currently scheduled for v3.8

**Comment by garethbowen** [comment] 2019-07-25 11:36
@maremegaye @Fatoufall @senseibara @amandacilek As Bara noted above it looks like this issue will be unnecessary once #5747 is delivered. After that if the label and value are both blank then it's probably a mistake in configuration so the current UI is acceptable. Given that I propose that we fix #5747 ASAP and close this issue. Please let me know if that's not acceptable.

**Comment by garethbowen** [comment] 2019-07-31 09:39
Ok. As there's been no response I'll assume that #5747 will fix the root cause so this fix is no longer required.

Please let me know if that's not the case.

**Closed by garethbowen** 2019-07-31 09:39 UTC
Labels: MUSO IN, Priority: 2 - Medium, Reports, Type: Bug
