### ISSUE TITLE
Moving contacts doesn't update the contact who will receive scheduled messages when no patient_id is set.  

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5824] opened 2019-07-19 16:37 UTC
**Describe the bug**
We introduced the option to move contacts to new parents in medic-conf. When a report is missing the `fields.patient_id` the doc won't update correctly to the new parent. This causes the scheduled messages to be sent to the previous contact who submitted the report originally. This would need to be updated so that it send to the correct contact under the new parent. 

**To Reproduce**
1. As an offline user. Go offline
2. Create a new female patient with standard config
3. Process a new pregnancy(this report should have no `fields.patient_id` because it is offline and sentinel hasn't given the patient_id)
4. Go online and sync.
5. Move the newly created patient to a new parent. 
6. Review the scheduled messages

**Expected behavior**
The scheduled messages should be updated to the new correct contact so when they are sent it is sent to the correct person. They currently will send to the original reporter. 

**Environment**
- Instance: gamma.dev
- Browser: chrome
- Client platform: linux
- App: webapp
- Version: 3.6.0

**Additional context**
From @dianabarsan 

> When hydrating a single doc (with fetchHydratedDoc) we end up with the fully hydrated patient lineage, including the primary contacts of the parents, but when fetching in bulk (with hydrateDocs) we end up with minified patient primary contacts lineage, which is required to map patient clinic correctly. The bulk hydration is used when scheduled messages are generated

**Comment by wtekeu** [comment] 2019-07-30 21:08
@garethbowen It looks like the primary contact could be referenced in many documents (reports) but not updated (ex: pregnancy report). I am wondering if we need to replace all these references (name, id). What do you think?
@kennsippell you may have an opinion since you worked on the initial implementation of `move-contacts`.

**Comment by garethbowen** [comment] 2019-07-31 02:41
I think you should not be able to move a contact if they are a primary contact for the place (unless you are also moving that place). The primary contact of a place that you're not moving shouldn't be automatically updated because we don't know who to pick as the primary.

I'm wondering if that's the issue though - I haven't looked at the code but it sounds like the patient is being moved but the message is being sent to their _old_ contact not the new one.

**Comment by kennsippell** [comment] 2019-07-31 06:14
From @dianabarsan's "context" above, it sounds like she suspected a bug in how we hydrate contacts, and not a bug in the `move-contacts` implementation...  That said, I suspect a reasonable fix here might be to update the `move-contacts` script to not allow moving contacts without an assigned patient_id (must wait for sentinel).

**Comment by dianabarsan** [comment] 2019-07-31 06:19
@kennsippell is right, the main bug is that our `lineage` shared library doesn't perform the bulk hydration correctly. This affects other functionality as well, for example incorrectly mapping recipients when processing scheduled messages.

**Comment by kennsippell** [comment] 2019-08-15 08:17
I've spent some time playing around with the lineage shared-lib as @dianabarsan suggested. I'm now circling back to @wtekeu's question above.

I am doing the following:

1. Create offline `user-A` associated with person `CHW-a` which is a child of place `clinic-A`
1. Create offline `user-B` associated with person `CHW-b` which is a child of place `clinic-B`
1. Login as `user-A`
1. Create new person `patient-1` (under `clinic-A`)
1. Register a pregnancy `report-1`
1. Move `patient-1` to have parent `clinic-B`
1. Login as `user-B`
1. Sync

Expect: `user-B` can see `patient-1` and `report-1`
Observed: `user-B` sees `patient-1` but not `report-1`

This occurs regardless of the state of the patient_id when creating the report. Although not mentioned in the original bug report, I believe this wasn't noticed until now because we have been logged in as a user which is the chlid of a `health_center`, and moving reports between clinics.

**Comment by dianabarsan** [comment] 2019-09-13 14:03
Ready for AT on `5824-lineage-patient-easy`.

This bug did not only affect reports about contacts that were moved, rather *any* report that satisfied these conditions:
a. The configured `recipient` is someone in the patient's lineage (like `grandparent` or `clinic`)
b. The sender(submitter) is someone who is outside the patient's lineage (could even be anonymous, if SMS and your form is public). 
The lineage library was refactored as part of this change, please also check that `contact-summary` receives correct information, in general SMS messages have correct recipients, etc.

**Comment by ngaruko** [comment] 2019-09-17 03:10
Not sure if I understood what changed in this issue @dianabarsan but I seem to see the same behaviour on the branch>

1. have two district: bede & ngaruko's district with bede & ngaruko as respective contact
2 . add a person to bede's district
3. create a pregnancy report for the person
4. move the person to ngaruko's district
5. check report => messages are still scheduled to be sent to `bede's number` ...

**Comment by dianabarsan** [comment] 2019-09-17 09:57
@ngaruko 
Can you please repeat the test with a patient at clinic level: move them from one clinic (that has a contact with a valid phone) to another clinic (that has a contact with a different valid phone).
If you're using standard config, the `ANC Reminders` are set to send messages to `clinic` (https://github.com/medic/medic/blob/master/config/standard/app_settings.json#L3190) which, in the case of a district level patient, will not resolve and default to the submitter.

**Comment by ngaruko** [comment] 2019-09-18 01:09
Thanks @dianabarsan Scheduled messages go to the new contact if they are at clinic level. Not sure if this was meant to be covered in the ticket: the patient's `parent` in the report still shows the old parent:
ie
on contact page: 
![image](https://user-images.githubusercontent.com/6979995/65095435-48ad5c00-da15-11e9-9d1d-2016392df886.png)

but on the report (original clinic):
![image](https://user-images.githubusercontent.com/6979995/65095491-83af8f80-da15-11e9-9e45-49ca93276a65.png)

**Comment by dianabarsan** [comment] 2019-09-18 06:29
@ngaruko 
This issue only covers correcting how report lineage is hydrated, thus resolving that correct "clinic" phone number when the contact is moved. 

Updating _possibly_ static fields in reports (like `CHW Name` and `CHW Phone Number`) would be part of the original "move contacts" issue (https://github.com/medic/medic-conf/issues/172). I believe it was not intended for those fields to be updated. Are you requesting they should?

**Comment by ngaruko** [comment] 2019-09-19 00:43
Agree @dianabarsan . That was not covered with the issue. I will close this and leave updating the other fields for another conversation...

**Closed** 2019-09-19 04:22 UTC
Labels: Priority: 1 - High, Type: Bug
