### ISSUE TITLE
Automated CouchDB db compaction is not working

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#3142] opened 2017-02-21 09:59 UTC

**Comment by garethbowen** [comment] 2017-02-21 10:00
http://docs.couchdb.org/en/2.0.0/config/compaction.html#compactions

**Comment by henokgetachew** [comment] 2017-02-21 10:03
Right now, the config we use for compaction is the following:
```_default = [{db_fragmentation, "70%"}, {view_fragmentation, "60%"}, {from, "23:00"}, {to, "04:00"}]
```
However, many instances are not doing automated compaction as pointed out by the medic-bot weekly check on fragmentation.
Plan:
1. Find the issue with the couchdb configuration or if it is a couchdb bug or a misconfiguration we're doing somewhere.
2. Write a medic bot plugin that does manual compaction if automated compaction hasn't been working well.

**Comment by browndav** [comment] 2017-02-21 18:21
This should probably be configured locally, rather than run from the outside (e.g. for later DIY instances, or instances we don't host). Once we figure out a configuration or process that works, we have `cron` and a few other mechanisms at our disposal to implement it locally.

**Comment by henokgetachew** [comment] 2017-03-08 11:37
Investigating this on lg instance, the error is caused by couch_compaction_daemon terminating because of timeout.:
```
[Tue, 07 Mar 2017 13:07:28 GMT] [error] [<0.11717.7>] ** Generic server couch_compaction_daemon terminating    
** Last message in was {'EXIT',<0.11718.7>,                                                                                                                     
                           {timeout,                                                                                    
                               {gen_server,call,[couch_server,get_server]}}}                                                                                    
** When Server state == {state,<0.11718.7>}                                                                    
** Reason for termination ==                                                                                                                                  
** {compaction_loop_died,                                                                                                                          
       {timeout,{gen_server,call,[couch_server,get_server]}}}                                                                                      
                                                                                                                                                                  
[Tue, 07 Mar 2017 13:07:28 GMT] [error] [<0.11717.7>] {error_report,<0.31.0>,                                                                                 
                       {<0.11717.7>,crash_report,                                                   
                        [[{initial_call,                                                           
                           {couch_compaction_daemon,init,['Argument__1']}},                                                                                     
                          {pid,<0.11717.7>},                                                                     
                          {registered_name,couch_compaction_daemon},                                       
                          {error_info,                                                                                     
                           {exit,                                                                                                                      
                            {compaction_loop_died,                                    
                             {timeout,                                                                         
                              {gen_server,call,[couch_server,get_server]}}},                                            
                            [{gen_server,terminate,7,                                                                                              
                              [{file,"gen_server.erl"},{line,804}]},                                            
                             {proc_lib,init_p_do_apply,3,                                           
                              [{file,"proc_lib.erl"},{line,237}]}]}},                              
                          {ancestors,                                                                    
                           [couch_secondary_services,couch_server_sup,                                                                                         
                            <0.32.0>]},                                                           
                          {messages,[]},                                                                 
                          {links,[<0.91.0>]},                                                                           
                          {dictionary,[]},                                       
                          {trap_exit,true},                                              
                          {status,running},                                     
                          {heap_size,987},                                       
                          {stack_size,27},                                              
                          {reductions,3113}],                                    
                         []]}}                                                                                      
[Tue, 07 Mar 2017 13:07:28 GMT] [error] [<0.91.0>] {error_report,<0.31.0>,                                                                             
                    {<0.91.0>,supervisor_report,                                      
                     [{supervisor,{local,couch_secondary_services}},                                                                                                                                                
                      {errorContext,child_terminated},                                                                    
                      {reason,                                                                           
                       {compaction_loop_died,                                          
                        {timeout,                                                                 
                         {gen_server,call,[couch_server,get_server]}}}},                             
                      {offender,                                                                         
                       [{pid,<0.11717.7>},                                                                                    
                        {name,compaction_daemon},                                                   
                        {mfargs,{couch_compaction_daemon,start_link,[]}},                            
                        {restart_type,permanent},                                                                                                                              
                        {shutdown,brutal_kill},                                          
                        {child_type,worker}]}]}}                                       
```

**Comment by henokgetachew** [comment] 2017-03-08 12:45
I have confirmed that the timeout issue occurs with both lg instances and with brac.  Three other instances had the compaction configuration commented out - easy fix, uncommenting the lines.  I'm investigating others that don't have obvious reasons.

**Comment by mandric** [comment] 2017-03-08 18:58
One thing worth pointing out in the docs is: "Before a compaction is triggered, an estimation of how much free disk space is needed is computed. This estimation corresponds to two times the data size of the database or view index. When there’s not enough free disk space to compact a particular database or view index, a warning message is logged."

**Comment by henokgetachew** [comment] 2017-03-09 08:59
Re: the `gen_server` timeout, it looks like this commit was meant to address it in the couchdb code: https://github.com/apache/couchdb/commit/c15fe1593ab99b439d2dfc187e6d0b0e20b985a8 Quoting here:

> Avoid gen_server call timeout error after compacting a database (seems to happen only for large DBs, but not always

**Comment by henokgetachew** [comment] 2017-03-09 09:00
According to this, it looks like the timeout cannot be increased: https://github.com/apache/couchdb-couch/pull/31

**Comment by henokgetachew** [comment] 2017-03-09 09:18
This is our default configuration on lg for the `os_process_timeout`
`os_process_timeout = 5000 ; 5 seconds. for view and external servers.`.
Right now it's 5 seconds.  We could change the default to may be 10 or 15 seconds or even one minute and see if the timeout stops happening and compaction runs successfully.  Our db is large enough to warrant a large increase.

**Comment by henokgetachew** [comment] 2017-03-10 11:35
The `os_process_timeout` for both lg instances and brac has now been changed to 60 seconds.  Will monitor the result to see if the automated compaction now runs well.

**Comment by sglangevin** [comment] 2017-05-05 21:11
@henokgetachew is this still being worked on or can we close it?

**Comment by henokgetachew** [comment] 2017-05-06 05:53
@sglangevin this is still going to be tracked.  The next update will be after disk size is grown for some of the instances.  Not all of the instances are doing compaction as they should right now.

**Comment by sglangevin** [comment] 2017-05-08 17:40
Sounds good! Just checking in as there hadn't been any activity here in a while.

**Comment by Hareet** [comment] 2019-02-20 09:15
Fairly certain 3.x projects are handling compaction correctly. But I'd like to confirm the large partner is handling it okay.

@henokgetachew Can you investigate on Muso Mali?

**Comment by henokgetachew** [comment] 2019-02-20 10:10
We ended up finding out that most of the compaction issues were caused by there not being enough free space.  Medic-bot gives weekly notifications about compaction not working correctly and muso hasn't been in that list in last week's test as well.  I'm going to close this as taken care of.

**Closed by henokgetachew** 2019-02-20 10:10 UTC
Labels: Type: Bug
