### ISSUE TITLE
Configurable place hierarchies

### ISSUE THREAD

**Issue by sglangevin** [medic/medic#3639] opened 2017-07-10 04:53 UTC
Originally reported in #118. Our current hierarchy is limited to 3 levels with hard-coded names. This creates a number of limitations in our deployments, particularly when trying to ensure that users have access to only the data they should/need to have access to. We've been working around this by creatively designing the hierarchy so that it works well enough, but what we really need is more levels to meet our partners' needs.

We should refactor our hierarchy so that every project can have the number of levels that it needs. This is also a precursor to being able to support the roles and permissions that are needed across the different health systems where we work.

Also: not sure how to categorize this feature request, so if anyone has suggestions, let me know! This issue hasn't been scheduled to a release yet.

**Comment by garethbowen** [comment] 2017-07-11 02:58
This also solves https://github.com/medic/medic-webapp/issues/857

**Comment by SCdF** [comment] 2018-01-22 14:02
In addition to multiple hierarchy levels, we would also want to support a specific white (and potentially black[1]) list of nodes in the hierarchy that the user is also allowed to see (or not see in the case of the blacklist).

For example, see this hierarchy:
![untitled 3](https://user-images.githubusercontent.com/583851/35223704-447fded6-ff7a-11e7-9e56-e22d8e72b88b.jpg)

A user might want to be configured so they can:
 - Have **C** as their primary location (and so see things in **C, H, I** and **J**)
 - Also see things at **K**, but not at **N** (so **K**, **L** and **M**).

One way to implement this is to have their facility configured as C, but also have an extra white list with K in it, and an extra black list with N in it.

However, we might also want to just remove the primary facility concept all together, and just have a list of white-listed facilities (here C and K) and a list of blacklisted ones (here N).

This feature could be used if, for example, a CHW leaves the program or is otherwise engaged, and another CHW needs to take over permanently / for a time:
 - The CHW already has access to C, and is fully replicated to the current max seq
 - An admin goes into their contact profile (or user, either works) and adds K to their list of facilities (and maybe adds N as a blacklist)
 - The CHW gets the update from the changes feed that their contact / user changed. From that the JS sees that a new facility has been added
 - We either:
    - Force PouchDB to start replicating from the start again, meaning that we will have to download the whole changes feed and the new docs again, but won't have to write much new code
    - Or write an API endpoint that gets all docs for a particular facility using the permissions of the requesting user, which involves writing more code but doesn't involve downloading the changes feed again

If we want to remove access, either due to the old CHW coming back or something else, this is a bit more challenging, as either:
 - We would have to improve PouchDB so it supports purging
 - We would have to do some monkey dance involving filtered replication between local PouchDB databases to clear out old data (and we'd have to be careful to not reset the replication point).

[1] AFAICT if we support whitelists (including removal of entries from the whitelist) it's trivial to also support blacklists, but it's not clear if that's actually something we want to do / something our partners need.

**Comment by SCdF** [comment] 2018-03-02 14:49
One thing to make sure we consider is how this affects analytics.

For example, if we allow variable hierarchies where places of the same type can have different numbers of parents[1] there may be certain types of "counting" based analytics that is harder.

Before we design this we should talk to @michaelkohn and work through these problems.

[1] One CHW has CHW Area -> Clinic -> District Hospital, and another has CHW Area -> District Clinic -> Clinic -> District Hospital

**Comment by sglangevin** [comment] 2018-03-02 17:13
We also have a request for being able to assign individual patients to a particular contact. So instead of assigning specific households to a CHW, assigning individual patients to another CHW who is part of a specific program. This happens frequently in HIV workflows where CHWs aren't following up on HIV+ patients. The follow-ups are done by another person, sometimes called a peer mentor or mentor mother, who is solely responsible for HIV follow-ups. This mentor needs access to HIV+ patients when she logs into our app so that she can conduct follow-ups. These patients span different households and may be in different CHW areas.

**Comment by michaelkohn** [comment] 2018-03-02 22:52
We should also look at other solutions in our space to look for inspiration and also consider the conversations about 'EMR style back-end'.

I'm not familiar with how OpenMRS deals with hierarchies, but the DHIS2 approach to this is pretty cool for analytics.  Essentially you can have an unlimited number of levels in your **Organization Unit** hierarchy.  Then you have **Groups** and **Group Sets** that allow you to categorize those Organization Units in many different ways... like geography or type.  The same **Organization Unit** can be in multiple **Groups**.  

![screen shot 2018-03-02 at 2 44 59 pm](https://user-images.githubusercontent.com/10096985/36925666-c3413478-1e28-11e8-8497-18e1c7b32c8d.png)

**Comment by SCdF** [comment] 2018-03-05 10:06
> We should also look at other solutions in our space to look for inspiration and also consider the conversations about 'EMR style back-end'.

We really need to kill the phrasing "EMR style back-end", unless we *actually* want to go there. The conversation we've had is about syncing to an EMR, not fundamentally changing the philosophy and technology behind our entire product. Syncing to an EMR is ~1 month's work, an EMR style back end is potentially years of work.

**Comment by SCdF** [comment] 2018-03-05 10:08
> We also have a request for being able to assign individual patients to a particular contact. So instead of assigning specific households to a CHW, assigning individual patients to another CHW who is part of a specific program. This happens frequently in HIV workflows where CHWs aren't following up on HIV+ patients.

Is this allowing a CHW to see that patient for the purpose of a HIV screening, but the patient is still seen / mostly managed by the general area CHW? I.e., is the current structure mostly right except for edge cases, or is the current structure basically wrong for a lot of workflows?

**Comment by sglangevin** [comment] 2018-03-05 18:11
The current structure is mostly right except for edge cases. HIV is a special workflow because it involves particularly sensitive health information. Currently, HIV services are often provided by a separate cadre of people who only deliver HIV services. In the future, this may change, but we've seen this in many of the programs we've worked with.

**Comment by sglangevin** [comment] 2018-07-11 21:42
Clarifying that this issue is just about having more hierarchy levels. We'll need to handle the permissions around who sees what people/places in another issue. I do think it's worth discussing how we can make sure we represent the government hierarchy in all of our projects, particularly those that have their own hierarchy that differs from that of the government (per Michael's comment).

**Comment by garethbowen** [comment] 2018-10-31 00:47
I've reviewed the requirements and put together a [spec for this feature](https://docs.google.com/document/d/1CQUu8eJdDvHGcJ_f3G0AUKHC_FONHoT5x-Q-q-EXZso/edit).

**Comment by garethbowen** [comment] 2019-02-20 08:23
Do this issue at the same time: https://github.com/medic/medic/issues/4926

**Comment by newtewt** [comment] 2019-07-23 13:16
I've found a few things so far but I'm still working on testing. 

Forms that create people when no person defined in the contact-type array causes an our error to be displayed when you try to edit.  Not sure if we should protect against that or not. 

Adding a duplicate element to the contact-type array shows a nice error in the console. In this case I copied the health_center contact-type twice. 

```
inbox.js:3 Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: type in group.types | orderBy: 'id' track by type.id, Duplicate key: health_center, Duplicate value: {"id":"health_center","name_key":"contact.type.health_center","group_key":"contact.type.health_center.plural","create_key":"contact.type.health_center.new","edit_key":"contact.type.place.edit","parents":["district_hospital"],"icon":"medic-health-center","create_form":"form:contact:health_center:create","edit_form":"form:contact:health_center:edit"}

```

In some cases, I'm struggling to get the parent populated. I'm not 100% sure if it's the form or the change.  When I have two health center types. I'm using the same form for both. The second will not populate the parent ID and when it makes calls I'm noticing the request as `GET https://localhost/medic/PARENT?`  This is using the health_center-create.xml in standard config. 


Another instance I created a second contact-type for person with the parent only for clinics. When I try to create a new person at the clinic level the parent is always set to the default in the form which is `PARENT` this is using the person-create.xml.

**Comment by newtewt** [comment] 2019-07-29 18:06
@garethbowen  I'm noticing this error when creating a person. This happens on the default config or the custom one I created. 

```
inbox.js:formatted:122623 Error in .on("change", function): TypeError: Cannot read property 'type' of undefined
    at Object.includes (inbox.js:formatted:121286)
    at Object.filter (inbox.js:formatted:114061)
    at inbox.js:formatted:120872
    at Array.forEach (<anonymous>)
    at inbox.js:formatted:120870
    at Wt.<anonymous> (inbox.js:formatted:120881)
    at inbox.js:formatted:2118
    at Wt.a.emit (inbox.js:formatted:2120)
    at inbox.js:formatted:98396
    at Object.Wt.e.onChange (inbox.js:formatted:98401)
``` 

I'm pretty sure it is erroring when hitting the following function in contact-types.js

```
    includes: doc => {
      return doc.type === 'contact' ||  // configurable hierarchy
             isHardcodedType(doc.type); // hardcoded hierarchy
    },
```

**Comment by garethbowen** [comment] 2019-07-30 03:16
Reproduced. It happens as an online user whenever there is a change in the DB while on the contacts page. This is due to a recent change where the admin doesn't include docs in the changes feed because it's too bandwidth intensive. Good catch!

I've updated the branch to fix this bug.

**Comment by newtewt** [comment] 2019-07-30 16:40
@garethbowen  is there a corresponding update to `medic-conf` for this change? The `appliesToType` on tasks, targets, contact summary, and I'm guessing elsewhere is passing `contact.type` everywhere. I'm guessing this needs to be change to be able to be backwards compatible so it passes `contact.type` or `contact.contact_type` as we've done in the webapp right? Otherwise the appliesToType would accept `contact` as a comparison but it would apply to any custom hierarchies and then need some other condition to filter based on the level in the hierarchy.

**Comment by garethbowen** [comment] 2019-07-31 02:21
You're absolutely right. I'll get right on this!

**Comment by garethbowen** [comment] 2019-07-31 09:11
I've made the changes to medic-conf in the above PR.

**Comment by newtewt** [comment] 2019-07-31 20:42
@garethbowen  if I were to create a person associated to a health_clinic. Then in the config remove the health_clinic as a parent to the person contact_type. What would the expected behavior be?  I'm seeing what the docs define when logged in as an offline user. Which causes them not to be displayed under the parent they were originally associated with.  When logged in as medic user I see those contacts displayed. I'm not sure if they should be the same or not. 

> If no parents then contacts of this type will be at the top of the hierarchy and cannot be added as a child of any contact.

**Comment by garethbowen** [comment] 2019-08-01 01:45
I don't think this is a supported use case. If I understand correctly then the person has a parent. But your contact_types configuration says the person should not have a parent.

Changing contact types requires updating all the contacts to be valid in the new hierarchy. Otherwise I'm not sure what the expected behaviour should be.

If you set up the contact_types first and then create contacts does it work as expected?

I'll add a note to the documentation PR about this.

**Comment by newtewt** [comment] 2019-08-01 12:26
> I don't think this is a supported use case. If I understand correctly then the person has a parent. But your contact_types configuration says the person should not have a parent.

That's correct. 

I think there is a discrepancy with new contact_types vs old in the situation outlined here. I'll prove that theory here in a moment and update.

**Comment by newtewt** [comment] 2019-08-01 14:11
@garethbowen  I think I have found another issue while trying to prove the above situation.  When trying to search for associated contact in create users the view for ddocs/medic-client/views/contacts_by_type_freetext/map.js is emitting by `doc.type` and when we send the key to that view we are sending what's defined in  `contact.types`. So either `people` or `person` in my case (watching the network calls in chrome). When I look at that view the custom types have a key of `["contact","people1"]` so it never returns. 

The line where I think the problem is. 

https://github.com/medic/medic/blob/5fdb97ca5db36a0583f536307316e89f1e9cf5fc/ddocs/medic-client/views/contacts_by_type_freetext/map.js#L10

**Comment by newtewt** [comment] 2019-08-01 14:46
Ok, so what I was thinking might be a problem isn't a problem. I was thinking that the legacy contact types would still show but it was a config issue. 

Creating a contact that is defined in contact_types and then removing works as expected.

**Comment by garethbowen** [comment] 2019-08-05 23:17
Merged into `medic`, `medic-docs`, and `medic-conf`.

**Closed** 2019-08-05 23:17 UTC
Labels: Priority: 2 - Medium, Type: Feature
