### ISSUE TITLE
relativeDays filter only shows days, not months etc (unlike relativeDate)

### ISSUE THREAD

**Issue by SCdF** [medic/medic#4626] opened 2018-06-13 10:14 UTC
To replicate, mucking around with the code is probably the easiest to see the change.

We have two relative time filters that we can use to output relative time based on an absolute time: `relativeDay` and `relativeDate`. From current usage and the code it looks like the intention is that one of them shows relative time including times earlier than "today", and the other does not. e.g. `relativeDate` would show "13 minutes ago" while `relativeDay` would just show "today".

However, there is also another difference that I think is unintentional: the largest time period `relativeDay` seems to support is days. That means it will output "55 days ago", as opposed to "2 months ago" like `relativeDate` would.

To me, the only difference between the two should be the minimum sized time period (seconds for `relativeDate`, days for `relativeDay`) and not the maximum.

**Comment by SCdF** [comment] 2018-06-13 10:14
@garethbowen interested if you know if this is intentional or not. It seems really weird

**Comment by garethbowen** [comment] 2018-06-13 10:16
I think this was intentional, but I'd have to check the usage and confirm with design to be sure.

**Comment by amandacilek** [comment] 2018-11-06 01:51
I can't speak to the full history of product discussions and needs etc. that led to these being the way they currently are. 

However, I do have an insight. I remember talking about this with Sharon in relation to UHC mode. In regards to that project, we decided that it was actually much more helpful to keep the information in _days_ rather than _months_, even beyond 30 days. Example: For UHC, there is a big difference between a household that was visited "33 days ago" and a household that was visited "60 days ago". Keeping the info in days provides more nuanced information vs. just saying "1 month ago" for both households.

In order to provide a recommendation for how these should be used moving forward I'd need to know how they are currently being used. In what situations do we currently use Relative Day and in what situations do we currently use Relative Date?

**Comment by garethbowen** [comment] 2018-11-06 02:06
@amandacilek relativeDay is used for things for which time doesn't make sense, for example, tasks use relativeDay because a task is due on a date not at a specific date and time. The task list is the only place relativeDay is used in the code but could be used in configuration in ways I have no idea about.

**Comment by garethbowen** [comment] 2019-07-26 11:36
Closing as by design. Please reopen if you need this!

**Closed by garethbowen** 2019-07-26 11:36 UTC
Labels: Blocked: waiting for design, Type: Bug
