### ISSUE TITLE
People card shows on a person's profile

### ISSUE THREAD

**Issue by kitsao** [medic/medic#5602] opened 2019-04-24 18:18 UTC
The `People` card shows on a contact of type person, with the status message `contact.no.children`.

**Steps to reproduce**:
1. Launch the webapp
2. Upload a `person-create` form...may use the [standard project](https://github.com/medic/medic/tree/master/config/standard)
3. Add a new person
4. View the profile of the person

**What should happen**:
 - Have the default cards (main card, tasks and reports) showing.

**What actually happens**:
 - An additional card, People is included and displayed
 - I have attached a screenshot of this observed behavior

**Environment**:
- Instance: _any running 3.4.0_
- Browser: _Chrome Version 73.0.3683.103 (64-bit)_
- Client platform: _Linux (Ubuntu 18.04)_
- App: _webapp_
- Version: _3.4.0_

**Other**:
_The same configs exhibit the expected behavior on app version 3.3.0. Has similarities to #3108_

![image](https://user-images.githubusercontent.com/3928714/56683206-be670300-66d5-11e9-98fc-0adc1224ac5d.png)

**Comment by Jodge** [comment] 2019-04-25 11:19
@kitsao  I have tracked that the People Card was added as part of implementing #5086 issue. 

@garethbowen the commit below that added the People's card seems to be an add-on to what was intended to be achieved on the original issue, could you shed some light on this since you may have better understanding as to why it was effected

https://github.com/medic/medic/commit/1d8ce7be236feb393d6dabdfee7de70fddd2d72b#diff-7e9d48e51139b82bcffd946f2ddcfaf7

**Comment by Jodge** [comment] 2019-04-25 11:34
The shifting of the scope of the piece of code below made the difference
```html
<div ng-if="selected.children.persons.length || selected.children.deceased.length">
```

**Comment by Jodge** [comment] 2019-04-25 12:47
@kitsao also not the People Card will always show whenever the selected person has an descendants i.e. the children will be listed

**Comment by kitsao** [comment] 2019-04-28 14:31
I wouldn't expect a person to have descendants though @Jodge. My understanding is that only 'place' contacts (`type = clinic/health_center/district_hospital`) should have the people card as per the note above. Unless things changed?

**Comment by garethbowen** [comment] 2019-04-28 22:02
@Jodge Yes it looks like that's the commit that did it. Unfortunately because we load the RHS asynchronously I suspect we can't tell if a contact has descendants until it's loaded. But @kitsao is correct, people never have descendants, so I think the fix would be to add something like `ng-if="selected.doc.type !== 'person'"` to the card so it never shows for people.

**Comment by Jodge** [comment] 2019-05-01 08:12
Ready for `AT` on branch `5602-people-card`

**Comment by wtekeu** [comment] 2019-05-08 15:08
Created a new person and verified that the People card is gone.

**Comment by wtekeu** [comment] 2019-05-08 15:08
Merged and ready for release.

**Comment by newtewt** [comment] 2019-06-20 14:35
I'm seeing the people card on a person doc again.  I see the code that was added to 

![image](https://user-images.githubusercontent.com/10531066/59857417-ec1f9f80-9346-11e9-8067-33effdc33c40.png)

The code added in the PR seems to be there and the doc.type for the doc is "type":"person"

![image](https://user-images.githubusercontent.com/10531066/59857485-0d808b80-9347-11e9-9694-2a2b881ed384.png)

**Comment by garethbowen** [comment] 2019-06-20 21:17
It looks like a merging issue - some redux refactoring broke this issue so they both worked separately and stopped working when they were combined. I'll have a look.

**Comment by garethbowen** [comment] 2019-06-21 01:16
Ready for AT in `3.5.x`

**Comment by newtewt** [comment] 2019-06-21 12:37
Cool, no longer seeing the people on a persons page.

**Comment by newtewt** [comment] 2019-07-15 17:32
The People section is showing on the Persons page in 3.6.0-beta.1


![image](https://user-images.githubusercontent.com/10531066/61235973-d6fb1e00-a704-11e9-8aea-ea4948a4f95e.png)

**Comment by garethbowen** [comment] 2019-07-15 21:20
There was a similar issue with the task count which should show in the person card when viewing a clinic so be sure to check that too, eg:

![Screenshot from 2019-07-16 09-20-32](https://user-images.githubusercontent.com/2064938/61250113-006e8500-a7ab-11e9-9ef5-7860ab8d3a90.png)

**Comment by newtewt** [comment] 2019-07-16 15:52
Cool the people list is gone from the person view and the tasks are showing on the clinic view.

**Closed by newtewt** 2019-07-16 15:52 UTC
Labels: Priority: 1 - High, Type: Bug
