### ISSUE TITLE
Update Ready dialogue always appears for online users in Firefox, and in private browsing modes for Chrome, Firefox

### ISSUE THREAD

**Issue by SCdF** [medic/medic#5315] opened 2019-01-30 12:08 UTC
To reproduce, use the app as an online user, either:
 - In Firefox, either normally or in private browsing
 - or in Chrome as Incognito

Whenever you refresh the app you will get a prompt that there are new changes and you should refresh.

NB: while we don't expect private browsing sessions to work with offline users, we do expect them to work with online ones.

From testing it appears to be because of this change:L https://github.com/medic/medic/commit/f401bd17acb23d91536da1d12726c03c1e06faa4, specifically that in these situations `$window.applicationCache.status === $window.applicationCache.UNCACHED`.

I'm tempted to just turn this back off, but it was added intentionally for #5247.

@garethbowen what do you know about this flag, and what it means? What situations did this flag fix for you?

**Comment by SCdF** [comment] 2019-01-30 12:16
Apparently we know about this: https://github.com/medic/medic/issues/5247#issuecomment-456141281

@garethbowen so is the situation that we don't support private browsing on any browser, or firefox at all, until we migrate to service workers?

**Comment by garethbowen** [comment] 2019-01-31 21:38
On it.

**Comment by garethbowen** [comment] 2019-02-01 03:13
I can reproduce this now. As far as I can tell the appcache is simply not working in Firefox. The line of code just made it really annoying because it prompts every time. I have yet to work out why it's not working...

**Comment by garethbowen** [comment] 2019-02-01 04:01
I've just tested on a real server on 3.3.0 which contains the UNCACHED change from #5247 and it's not affected. The "The operation is insecure." error is either due to our development environment not be https and maybe Firefox has changed recently to not like that, _or_ because of our more aggressive CSP but I commenting out the CSP didn't resolve this issue.

I'd like to get a production like server on to alpha so I can test the newest CSP settings with the new appcache settings _and_ https and see if I can reproduce it.

We used to use alpha.dev for this - @Hareet / @henokgetachew Can we get a new instance spooled up at alpha.dev.medicmobile.org that we can keep on the latest for testing?

**Comment by garethbowen** [comment] 2019-02-08 03:07
@ngaruko @newtewt Have either of you noticed this issue on 3.3.x?

**Comment by newtewt** [comment] 2019-02-08 15:13
I've only seen it in the situation described in 5427. Spent some time trying to get it to happen on gamma.dev(3.3.0-beta.3) with firefox and incognito chrome. I did not see this occurring.

**Comment by garethbowen** [comment] 2019-02-10 21:45
@SCdF It sounds like this only affects dev environments, and it should be fixed once and for all by service workers. Are you happy for me to close it out?

**Closed** 2019-02-11 09:48 UTC
Labels: Priority: 1 - High, Type: Bug, firefox
