### ISSUE TITLE
CouchDB 2.1.2 internal error: mfa: fabric_rpc:all_docs/3 exit:timeout

### ISSUE THREAD

**Issue by ghost** [medic/medic#4757] opened 2018-07-25 23:29 UTC
We are encountering https://github.com/apache/couchdb/issues/1119 routinely in our v3 environment. This is a blocker. Further discussion is available in shadow issue https://github.com/medic/medic-infrastructure/issues/4.

An attempt at obtaining additional debug information is available in https://github.com/apache/couchdb/pull/1245. CouchDB maintainers have advised to wait for v2.2.0.

**Comment by garethbowen** [comment] 2018-07-25 23:51
@browndav Do you mean couchdb 2.2.0 or 2.3.0? [This comment](https://github.com/apache/couchdb/issues/1119#issuecomment-405014044) says 2.2.0 which is much sooner...

**Comment by garethbowen** [comment] 2018-07-25 23:54
Can we build a 2.2.0 alpha version to get the additional info?

**Comment by browndav** [comment] 2018-07-26 00:07
Sorry, corrected the typo: you're correct, it's v2.2.0.

**Comment by browndav** [comment] 2018-08-15 18:56
Well, good news: the problem is now new and different. As best as I can tell an undocumented timeout setting has nailed the original problem, but now we're consistently failing to bootstrap the `_users` database (previously successful on 2.1.1 and 2.1.2 with no changes on our side). Will continue to follow up.

**Comment by garethbowen** [comment] 2018-09-17 04:30
@Hareet Do we think the increased timeout workaround is sufficient and this issue can be closed or is there still more work to do here?

**Comment by sergey-safarov** [comment] 2018-11-21 23:45
This page may be key for understanding of slow performance of dockerized app
https://sysdig.com/blog/container-isolation-gone-wrong/ 
and this [ticket maybe related](https://github.com/apache/couchdb/issues/1125)

**Comment by garethbowen** [comment] 2019-02-12 03:16
Closing as a duplicate of medic/medic-infrastructure#4

**Closed by garethbowen** 2019-02-12 03:16 UTC
Labels: Blocked, Blocked: waiting for info, Blocked: waiting for triage, Priority: 1 - High, Type: Bug, Type: Technical issue, Upgrading

**Comment by sergey-safarov** [comment] 2019-02-12 07:23
Reference ticket public is not accessible.
Looks as other guys not be able to track this ticket.
