### ISSUE TITLE
api produces empty changes responses sometimes (e.g. after upgrade)

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#4154] opened 2018-02-01 17:06 UTC
Seen with a very big database, after `medic` and `medic-client` views have been indexed:

# Errors seen

<img width="745" alt="screen shot 2018-02-01 at 17 43 49" src="https://user-images.githubusercontent.com/191496/35691488-db131574-0778-11e8-803a-87f04a1f524d.png">

and "copied as cURL":

```
$ curl 'http://my_user:pass@localhost:5988/medic/_changes?timeout=595000&style=all_docs&heartbeat=10000&filter=_doc_ids&since=0&limit=100' -H 'Accept: application/json' -H 'Referer: http://localhost:5988/medic/_design/medic/_rewrite/' -H 'Origin: http://localhost:5988' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36' -H 'Content-Type: application/json' --data-binary '{"doc_ids":["org.couchdb.user:my_user"]}' --compressed
curl: (52) Empty reply from server
```

## Observations 

It seems like api takes some time to warm up.  In my case this was a couple of hours, with ~800,000 docs in the db.

Until api has warmed up, it gives garbage responses, and appears to show nothing of note in the logs.  After a couple of hours it came good, and started responding as expected.

After it's started working, it will immediately work after restarting `api`.  As `api` has no persistent state, this suggests there is something couchy going on.

# Recreating

I'm not currently keen to repeat this experience immediately, as regenerating views takes a couple of hours, but I have observed it with both couch `2.1.1` and `1.6.1`, and I'm confident it can be recreated reliably.

* Sentinel was not running when this bug was observed.
* Using api `2.12.0`, locally.

# Some speculation

It may be there was a ddoc/view which I failed to warm before starting my testing, although I don't think that was the case.  Also API won't start until `_design/medic-client` at least has warmed, and this takes much more time than for `_design/medic`.  So likely both were already fine.

**Comment by SCdF** [comment] 2018-02-02 07:41
@alxndrsn was there anything in the api logs?

**Comment by alxndrsn** [comment] 2018-02-02 08:29
@scdf as above:

> Until api has warmed up, it gives garbage responses, and appears to show nothing of note in the logs.

**Comment by alxndrsn** [comment] 2018-02-06 10:18
I think this may occur every time `medic-api` starts up - probably it's loading the changes feed into api.

<img width="1056" alt="screen shot 2018-02-06 at 11 15 43" src="https://user-images.githubusercontent.com/191496/35853975-4f60e0be-0b2f-11e8-9f63-cd092821e626.png">

<img width="1054" alt="screen shot 2018-02-06 at 11 18 12" src="https://user-images.githubusercontent.com/191496/35854043-7da06756-0b2f-11e8-84ff-3c92f7226a27.png">


```
curl: (52) Empty reply from server
```

**Comment by rmhowe** [comment] 2018-02-21 14:58
@alxndrsn can you add status and priority labels?

**Comment by garethbowen** [comment] 2018-06-25 18:56
@dianabarsan Do you think this will still happen on the rewritten changes controller?

**Comment by dianabarsan** [comment] 2018-07-03 07:52
Theoretically, because we're using Pouch to request changes, even if Couch sends garbage, responses sent by API should, at least, be of proper form.

**Comment by dianabarsan** [comment] 2018-07-04 15:30
The only way I managed to get an empty response was to execute your indicated request with an admin user's credentials. 
Because `POST` requests to `_changes` are `bodyParsed` before being proxied to CouchDB, with the `req` stream already consumed by the `bodyParser`, no `body` ever reached CouchDB and the manifestation is exactly this. 

@alxndrsn Do you think this could have happened here?

**Comment by alxndrsn** [comment] 2018-07-04 16:22
> Do you think this could have happened here?
It's possible!  Sorry for not being clearer which type of user was being used in my report.

**Comment by garethbowen** [comment] 2019-04-02 04:08
@dianabarsan I think this should be closed as ancient or can't reproduce. What do you think?

**Comment by dianabarsan** [comment] 2019-04-02 07:16
I agree. Maybe `ancient` as I could reproduce if I POST-ed as an Admin user.

**Closed** 2019-04-02 08:52 UTC
Labels: Type: Bug, Won't fix: Ancient
